import { adminRoutes } from "@/config/routes";

import type { ManualSection } from "./manualTypes";

/** 관리자 화면 매뉴얼 — 실제 adminMenu / adminRoutes 기준 */
export const ADMIN_MANUAL_SECTIONS: ManualSection[] = [
  {
    id: "admin-dashboard",
    title: "1. 관리자 대시보드",
    menuPath: "Dashboard",
    route: adminRoutes.dashboard,
    status: "available",
    purpose: "시스템·리스크·운영 요약과 이상 징후를 먼저 확인합니다.",
    prerequisites: ["admin 역할 로그인"],
    steps: [
      "`/admin/dashboard`에서 Health·리스크·주요 카운트를 확인합니다.",
      "이상 있으면 운영센터·Recovery·리스크로 이동합니다.",
    ],
    buttons: ["새로고침"],
    normalState: ["대시보드 로드 성공"],
    errors: ["권한 오류 → admin 역할·permission 확인"],
    liveImpact: "조회 전용입니다.",
    nextSteps: ["회원관리에서 계정·권한을 점검합니다."],
  },
  {
    id: "admin-members",
    title: "2. 회원관리",
    menuPath: "회원관리 → 회원관리/권한관리",
    route: adminRoutes.members,
    status: "available",
    purpose:
      "회원 조회·권한·활성/비활성, 테스트 계정 정리 Preview를 수행합니다.",
    prerequisites: ["menu:members", "자기 자신 삭제 금지 정책 이해"],
    steps: [
      "회원 목록에서 역할·활성 상태를 조회합니다.",
      "`권한관리`에서 역할을 조정합니다.",
      "테스트 계정 정리 Preview에서 연결 데이터 건수를 확인합니다.",
      "보호 계정(`admin`, `kikicom` 로그인 ID 정확일치)은 삭제/비활성 대상에서 제외됩니다.",
      "기본 정책은 비활성화/소프트 삭제입니다. Hard delete는 참조 0건·별도 정책만.",
      "execute는 확인문구·백업 확인 후에만 가능하며, 운영에서 자동 삭제하지 않습니다.",
    ],
    buttons: ["활성/비활성", "Preview", "확인 후 실행(승인 시에만)"],
    normalState: ["Preview만으로는 DB 변경 없음"],
    errors: ["PROTECTED_USERNAME / SELF_DELETE_FORBIDDEN"],
    liveImpact: "계정 비활성은 해당 사용자 주문을 중단시킬 수 있습니다.",
    nextSteps: ["계좌 메뉴에서 UBA·브로커를 점검합니다."],
  },
  {
    id: "admin-accounts",
    title: "3. 계좌관리",
    menuPath: "계좌 → 전체/키움/업비트",
    route: adminRoutes.accounts,
    status: "available",
    purpose: "Paper·키움·업비트·UBA·Credential·Recovery 상태를 관리합니다.",
    prerequisites: ["브로커 설정", "UBA 바인딩 정책"],
    steps: [
      "`전체 계좌`에서 Paper/UBA를 조회합니다.",
      "`키움 계좌` / `업비트 계좌`에서 Credential 검증·잔고 스냅샷·Recovery를 확인합니다.",
      "업비트 시세는 `시장 데이터 → 업비트 시세`로 분리되어 있습니다.",
    ],
    buttons: ["연결 테스트", "잔고 동기화", "Recovery 점검"],
    normalState: ["검증 성공", "스냅샷 갱신"],
    errors: ["인증 실패 → Credential 재등록(Secret 화면 노출 금지)"],
    liveImpact: "계좌 검증만으로 LIVE 주문이 켜지지 않습니다. LIVE Flag는 기본 OFF입니다.",
    nextSteps: ["시장 데이터·기술지표를 확인합니다."],
  },
  {
    id: "admin-market",
    title: "4. 시장 데이터",
    menuPath: "시장 데이터 → 모니터링/뉴스/공시/업비트 시세/기술지표",
    route: adminRoutes.upbitMarkets,
    status: "available",
    purpose: "시세·뉴스·공시와 기술지표 파라미터 CRUD를 관리합니다.",
    prerequisites: ["시장 수집 Job 정상"],
    steps: [
      "`업비트 시세`에서 KRW 마켓·종목 동기화를 확인합니다.",
      "`기술지표 관리`에서 SMA/EMA/RSI/MACD 등 파라미터를 등록·수정합니다.",
      "잘못된 파라미터는 Fail Closed(시스템 기본값 유지)입니다.",
      "`시스템 기본값 복원`은 활성 DB 설정을 끄고 Default로 되돌립니다.",
      "Preview로 적용값을 검증한 뒤 계산 재실행은 별도 배치 버튼으로 수행합니다.",
      "승인된 전략 Definition Snapshot과 혼동하지 않습니다.",
    ],
    buttons: ["파라미터 등록", "수정", "비활성", "기본값 복원", "Preview", "배치 실행"],
    normalState: ["활성 버전 Badge", "resolved_engine_params 표시"],
    errors: ["MACD fast≥slow → 422", "음수 기간 → 422"],
    liveImpact: "지표 파라미터 변경은 과거 승인 전략 재현성을 깨지 않도록 Snapshot과 분리됩니다.",
    nextSteps: ["전략·후보 파이프라인을 진행합니다."],
    notes: [`경로: ${adminRoutes.indicators}`],
  },
  {
    id: "admin-ai-candidates",
    title: "5. 후보 및 AI",
    menuPath: "전략·후보 → 후보·LLM / Lifecycle / …",
    route: adminRoutes.ai,
    status: "available",
    purpose: "Candidate·Lifecycle·Strategy Request 심사까지 AI 파이프라인을 운영합니다.",
    prerequisites: ["AI Provider(또는 Mock)", "menu:ai"],
    steps: [
      "Provider/Prompt/Policy/Execution을 점검합니다.",
      "Candidate Assessment·Consensus·Recommendation Queue·Promotion을 순서대로 확인합니다.",
      "`Candidate Lifecycle`에서 상태 전이를 관리합니다.",
      "`Strategy Request 심사`(`/admin/strategy-requests`)에서 사용자 요청을 승인·반려합니다.",
    ],
    buttons: ["실행", "승인", "반려", "Lifecycle 전이"],
    normalState: ["요청 상태가 감사 로그와 함께 갱신"],
    errors: ["Provider 오류 → Mock/로컬 Ollama 확인"],
    liveImpact: "후보·요청 단계는 실주문을 만들지 않습니다.",
    nextSteps: ["Strategy Draft·Definition으로 진행합니다."],
    notes: [
      `Strategy Request: ${adminRoutes.strategyRequests}`,
      `Strategy Draft: ${adminRoutes.strategyDrafts}`,
    ],
  },
  {
    id: "admin-strategies",
    title: "6. 전략 관리",
    menuPath: "전략·후보 → 전략관리 / Draft",
    route: adminRoutes.strategies,
    status: "available",
    purpose: "Draft·Definition 검토·승인·반려, 공개/비공개, 계좌 연결을 관리합니다.",
    prerequisites: ["승인된 Strategy Request 또는 Draft"],
    steps: [
      "`Strategy Draft 관리`에서 버전을 검토합니다.",
      "`전략관리`에서 Definition 승인·공개 범위를 설정합니다.",
      "계좌 연결은 사용자/관리자 계좌 화면과 연동됩니다.",
    ],
    buttons: ["승인", "반려", "버전 비교", "공개/비공개"],
    normalState: ["승인 후 검증 파이프라인 진입 가능"],
    errors: ["미승인 Draft로 Activation 시도 → 차단"],
    liveImpact: "승인만으로 Runtime이 자동 시작되지 않습니다.",
    nextSteps: ["백테스트·품질 검증을 수행합니다."],
  },
  {
    id: "admin-validation",
    title: "7. 전략 검증",
    menuPath: "백테스트 / Portfolio Validation 등",
    route: adminRoutes.backtests,
    status: "available",
    purpose:
      "Backtest, Performance, Walk-Forward, Quality Gate, Sensitivity, Monte Carlo, Portfolio Validation을 수행합니다.",
    prerequisites: ["승인된 Draft/Definition"],
    steps: [
      "`백테스트`를 실행하고 성과를 확인합니다.",
      "Walk-Forward·Quality Gate·Parameter Sensitivity·Monte Carlo 결과를 검토합니다.",
      "`Portfolio Validation`(`/admin/portfolio-validations`)으로 복수 전략 조합을 검증합니다.",
    ],
    buttons: ["실행", "리포트 조회", "게이트 통과/실패 확인"],
    normalState: ["게이트 PASS/FAIL이 명확"],
    errors: ["FAIL → Promotion 금지"],
    liveImpact: "검증 실패 전략을 LIVE에 올리지 않습니다.",
    nextSteps: ["Human Decision → Promotion으로 진행합니다."],
  },
  {
    id: "admin-promotion",
    title: "8. 승인 및 운영 등록",
    menuPath: "전략·후보 파이프라인 (Decision → Operation Readiness)",
    route: adminRoutes.strategyDrafts,
    status: "admin_approval",
    purpose:
      "Human Decision, Promotion Commit, Activation, Runtime Registration, Deployment/Operation Readiness를 확정합니다.",
    prerequisites: ["검증 게이트 통과"],
    steps: [
      "Human Decision으로 승인/반려를 기록합니다.",
      "Promotion Commit으로 배포 가능한 상태로 고정합니다.",
      "Activation·Runtime Registration을 수행합니다.",
      "Deployment Readiness·Operation Readiness를 확인합니다.",
    ],
    buttons: ["승인", "Commit", "Activate", "Register", "Readiness 확인"],
    normalState: ["각 단계 상태가 순차적으로 READY"],
    errors: ["선행 단계 누락 → 차단"],
    liveImpact: "이 단계 후에도 LIVE Flag가 자동 ON 되지 않습니다.",
    nextSteps: ["Runtime·Scheduler에서 시작 조건을 맞춥니다."],
  },
  {
    id: "admin-runtime",
    title: "9. Runtime 및 Scheduler",
    menuPath: "거래 → 자동매매관리 / 리스크·운영 → 스케줄러·운영센터",
    route: adminRoutes.trading,
    status: "conditional",
    purpose:
      "Scope별 Runtime 시작·중지, MARKET_OPEN/CLOSE, Upbit 24/7, 자동시작 Flag, 중복 실행 방지를 운영합니다.",
    prerequisites: ["Operation Readiness", "계좌·전략 링크", "리스크 Gate"],
    steps: [
      "`자동매매관리`에서 Scope를 선택하고 START/STOP합니다.",
      "주식은 MARKET_OPEN/CLOSE, 업비트는 24/7 특성을 반영합니다.",
      "자동 시작 Flag는 명시적으로 관리하며, 중복 실행을 방지합니다.",
      "`스케줄러 관리`·`운영센터`에서 Job/Health를 확인합니다.",
    ],
    buttons: ["START", "STOP", "Job 실행", "Health"],
    normalState: ["단일 active runtime", "중복 없음"],
    errors: ["중복 실행 감지 → 즉시 STOP"],
    liveImpact: "Runtime START는 허용된 모드에서만 주문을 생성합니다. LIVE는 기본 OFF입니다.",
    nextSteps: ["리스크·Recovery를 상시 모니터링합니다."],
  },
  {
    id: "admin-risk-ops",
    title: "10. 리스크·운영",
    menuPath: "리스크·운영 → 리스크/LIVE검증/운영센터/장애복구",
    route: adminRoutes.risk,
    status: "available",
    purpose:
      "시스템 Risk, Kill Switch, Account Pause, LIVE Unlock, Recovery Conflict, Reconciliation을 통제합니다.",
    prerequisites: ["운영 권한"],
    steps: [
      "`리스크 관리`에서 Kill Switch·한도를 설정합니다.",
      "LIVE Unlock은 명시적 승인 절차 후에만 수행합니다(매뉴얼이 Flag ON을 직접 지시하지 않음).",
      "`장애 복구`에서 Conflict·Reconciliation을 처리합니다.",
      "`업비트 소액 LIVE 검증`은 별도 승인·검증 경로입니다.",
    ],
    buttons: ["Kill Switch ON/OFF", "Account Pause", "Unlock(승인 후)", "Reconciliation"],
    normalState: ["Gate 통과 주문만 허용"],
    errors: ["Conflict 미해결 → Runtime 재개 금지"],
    liveImpact: "Kill Switch는 즉시 신규 주문을 막습니다.",
    nextSteps: ["주문·원장을 대조합니다."],
  },
  {
    id: "admin-orders-ledger",
    title: "11. 주문·체결·원장",
    menuPath: "거래 → 주문관리/거래내역/잔고·손익",
    route: adminRoutes.orders,
    status: "available",
    purpose: "주문 상태·체결·Position·Balance·PnL을 Paper/MOCK/LIVE로 구분해 감사합니다.",
    prerequisites: ["계좌·Runtime 이력"],
    steps: [
      "주문관리에서 상태 전이를 확인합니다.",
      "거래내역·잔고·손익으로 원장을 대조합니다.",
      "전략 Provenance가 없는 건은 미식별로 남깁니다(임의 채움 금지).",
    ],
    buttons: ["조회", "필터", "동기화"],
    normalState: ["원장·브로커 잔고 일치"],
    errors: ["불일치 → Recovery"],
    liveImpact: "관리자 조회·동기화가 추가 주문을 만들지 않도록 정책을 지킵니다.",
    nextSteps: ["운영센터 상태를 확인합니다."],
  },
  {
    id: "admin-ops-center",
    title: "12. 운영센터",
    menuPath: "리스크·운영 → 운영센터 / 운영관리",
    route: adminRoutes.operations,
    status: "conditional",
    purpose:
      "Health, Release Readiness, Runtime, Worker, Scheduler, Recovery, WebSocket, Queue/Outbox를 점검합니다.",
    prerequisites: ["ops 권한"],
    steps: [
      "운영센터에서 live 타일(Health·Scheduler·Broker·DB 등)을 엽니다.",
      "Backup Dump / Restore / 앱 Log Tail은 Planned·Disabled입니다. 웹에서 실행하지 않습니다.",
      "관련 화면: DB 관리, 로그 조회(감사 로그). CLI 매뉴얼은 저장소 docs/manual 참고.",
    ],
    buttons: ["열기(실 API)", "관련 화면", "Disabled(미구현)"],
    normalState: ["실 API 타일만 활성"],
    errors: ["미구현 버튼 활성 상태면 버그로 보고"],
    liveImpact: "운영센터 자체는 주문을 생성하지 않습니다.",
    nextSteps: ["장애 대응 탭의 안전 종료 절차를 숙지합니다."],
    notes: [
      "Backup/Restore/Log Tail = 계획됨/미구현",
      `문서 CMS: ${adminRoutes.docs}`,
    ],
  },
];
