import { userRoutes } from "@/config/routes";

import type { ManualSection } from "./manualTypes";

/** 사용자 화면 매뉴얼 — 실제 userMenu / userRoutes 기준 */
export const USER_MANUAL_SECTIONS: ManualSection[] = [
  {
    id: "user-login-dashboard",
    title: "1. 로그인과 사용자 대시보드",
    menuPath: "대시보드",
    route: userRoutes.dashboard,
    status: "available",
    purpose: "로그인 후 계좌·포지션·알림 요약을 한눈에 확인합니다.",
    prerequisites: ["계정 발급 또는 회원가입 완료", "백엔드/프론트 기동"],
    steps: [
      "`/login`에서 아이디·비밀번호로 로그인합니다.",
      "역할이 user/trader면 `/user/dashboard`로 이동합니다.",
      "대시보드에서 계좌·관심종목·알림 상태를 확인합니다.",
    ],
    buttons: ["로그인", "로그아웃"],
    normalState: ["대시보드 카드가 로드됨", "세션 토큰이 유지됨"],
    errors: [
      "401 → 비밀번호/계정 확인",
      "리다이렉트 루프 → 역할이 admin-only인지 확인",
    ],
    liveImpact: "로그인만으로는 실거래 주문이 발생하지 않습니다.",
    nextSteps: ["내 계좌에서 Paper/브로커 계좌를 등록합니다."],
  },
  {
    id: "user-accounts",
    title: "2. 내 계좌",
    menuPath: "내 계좌 → 전체/키움/업비트/Paper",
    route: userRoutes.accounts,
    status: "available",
    purpose:
      "Paper·키움 MOCK/LIVE·업비트 계좌를 등록하고 Credential·리스크·전략 연결을 관리합니다.",
    prerequisites: ["로그인", "브로커 Credential(실연동 시)"],
    steps: [
      "`내 계좌 → Paper 계좌`에서 Paper 계좌를 생성합니다.",
      "`키움 계좌` / `업비트 계좌`에서 계좌를 등록하고 Credential을 검증합니다.",
      "계좌 상태(연결·Recovery)·마스킹된 계좌번호를 확인합니다.",
      "계좌별 리스크 한도를 설정합니다.",
      "승인된 전략을 계좌에 연결합니다(Account Strategy Link).",
    ],
    buttons: ["계좌 등록", "Credential 검증", "기본 계좌 설정", "전략 연결"],
    normalState: [
      "Credential 검증 성공",
      "Paper는 즉시 사용 가능",
      "LIVE는 Flag/Unlock 전까지 주문 불가",
    ],
    errors: [
      "검증 실패 → API Key/Secret·권한 재확인(화면에 Secret 재표시 없음)",
      "UBA 미연결 → 관리자에게 계좌 바인딩 요청",
    ],
    liveImpact:
      "Credential 저장·검증은 실주문과 무관합니다. LIVE 주문은 별도 Flag·승인 후에만 가능합니다.",
    nextSteps: ["시장 정보에서 시세를 확인합니다."],
    notes: [
      `경로: ${userRoutes.accountsPaper}, ${userRoutes.accountsKiwoom}, ${userRoutes.accountsUpbit}`,
    ],
  },
  {
    id: "user-market",
    title: "3. 시장 정보",
    menuPath: "시장 정보 → 주식/암호화폐/관심종목/뉴스/공시",
    route: userRoutes.marketsStocks,
    status: "available",
    purpose: "주식·업비트 시세, 현재가·거래량·갱신 시각, WebSocket 상태를 조회합니다.",
    prerequisites: ["로그인", "시장 데이터 수집 정상"],
    steps: [
      "`주식` / `암호화폐`에서 종목을 검색합니다.",
      "현재가·등락률·거래량·데이터 갱신 시각을 확인합니다.",
      "WebSocket/실시간 상태를 확인합니다.",
      "관심종목·뉴스·공시를 보조 정보로 활용합니다.",
      "기술지표는 관리자 파라미터 설정을 따르며, 사용자 화면에서는 조회 중심으로 사용합니다.",
    ],
    buttons: ["검색", "새로고침", "관심종목 추가"],
    normalState: ["시세 테이블 갱신", "갱신 시각이 최신"],
    errors: ["시세 공백 → 관리자 모니터링·업비트 시세 화면 확인"],
    liveImpact: "시세 조회만으로는 주문이 발생하지 않습니다.",
    nextSteps: ["매매 후보에서 종목을 검토합니다."],
  },
  {
    id: "user-candidates",
    title: "4. 매매 후보",
    menuPath: "매매 후보 → 주식/업비트/LLM 분석",
    route: userRoutes.candidatesStocks,
    status: "available",
    purpose: "후보(Candidate) 상태와 LLM 분석을 보고 Strategy Request 생성으로 이어갑니다.",
    prerequisites: ["시장 데이터 확인", "(선택) AI Provider 가동"],
    steps: [
      "`주식 후보` / `업비트 후보`에서 후보 목록·상태를 확인합니다.",
      "`LLM 분석`에서 분석 결과를 참고합니다.",
      "유망 후보에 대해 `전략 요청`(`/user/strategy-requests`)을 생성합니다.",
    ],
    buttons: ["후보 새로고침", "전략 요청 생성"],
    normalState: ["Candidate 상태 표시", "요청이 PENDING 등으로 저장"],
    errors: ["AI 실패 → Provider/Mock 상태 확인(관리자)"],
    liveImpact: "후보·요청 생성은 실주문을 만들지 않습니다.",
    nextSteps: ["내 전략에서 요청·초안·승인 상태를 추적합니다."],
    notes: [`전략 요청: ${userRoutes.strategyRequests}`, `전략 초안: ${userRoutes.strategyDrafts}`],
  },
  {
    id: "user-strategies",
    title: "5. 내 전략",
    menuPath: "내 전략 → 전략/자동매매/백테스트",
    route: userRoutes.strategies,
    status: "conditional",
    purpose: "전략·자동매매·백테스트를 관리하고 계좌 연결·Runtime 상태를 확인합니다.",
    prerequisites: ["Strategy Request 또는 승인된 Definition", "계좌 등록"],
    steps: [
      "`전략`에서 내 전략·승인 상태를 확인합니다.",
      "`전략 요청`/`전략 초안` 화면에서 관리자 검토 진행 상황을 봅니다.",
      "승인된 전략을 계좌에 연결합니다.",
      "`자동매매`에서 Runtime/실행 상태를 확인합니다(시작은 권한·Gate에 따름).",
      "`백테스트`로 과거 성과를 참고합니다(실계좌 성과와 별개).",
    ],
    buttons: ["전략 연결", "자동매매 상태 확인", "백테스트 실행/조회"],
    normalState: ["승인·연결 상태 명확", "Runtime STOP/RUNNING 표시"],
    errors: ["승인 전 시작 불가 → 관리자 승인·Activation 필요"],
    liveImpact:
      "자동매매 시작은 Paper/MOCK/Shadow와 LIVE가 다릅니다. LIVE는 기본 OFF이며 관리자 Unlock이 필요합니다.",
    nextSteps: ["주문·체결에서 실행 결과를 확인합니다."],
  },
  {
    id: "user-orders",
    title: "6. 내 주문·체결",
    menuPath: "내 주문·체결 → 매매/주문·체결/키움/업비트",
    route: userRoutes.orders,
    status: "available",
    purpose:
      "수동 주문 실행, 주문·체결 목록, 취소·정정, 계좌별 전략 성과를 확인합니다.",
    prerequisites: ["계좌 선택", "Paper 또는 허용된 실행 모드"],
    steps: [
      "`매매(주문 실행)`에서 계좌·종목·수량을 입력해 주문을 제출합니다.",
      "`주문·체결 내역`에서 상태(CREATED/ACCEPTED/FILLED/CANCELLED 등)를 확인합니다.",
      "키움/업비트 전용 화면에서 브로커별 내역을 봅니다.",
      "계좌별 전략 성과에서 전략별 주문·체결·실현손익을 확인합니다.",
      "전략 ID가 없는 체결은 `전략 미식별`로 표시됩니다.",
      "Paper / MOCK / Shadow / LIVE 라벨을 구분해 해석합니다.",
    ],
    buttons: ["주문 제출", "취소", "정정", "성과 조회", "기간 필터"],
    normalState: ["주문 상태 전이 정상", "성과 source=ACCOUNT_LEDGER_NOT_BACKTEST"],
    errors: [
      "거절 → 리스크/Kill Switch/잔고 확인",
      "미체결 잔존 → 취소 또는 거래소 수동 확인",
    ],
    liveImpact:
      "Paper는 시뮬레이션입니다. LIVE 주문은 Flag·승인·리스크 게이트를 통과한 경우에만 가능합니다.",
    nextSteps: ["잔고·손익에서 Position/PnL을 확인합니다."],
  },
  {
    id: "user-portfolio",
    title: "7. 내 잔고·손익",
    menuPath: "내 잔고·손익",
    route: userRoutes.portfolio,
    status: "available",
    purpose: "Position, 사용가능 현금, 평가금액, 실현/미실현 손익, 전략별 성과를 봅니다.",
    prerequisites: ["계좌에 체결 이력 또는 잔고 스냅샷"],
    steps: [
      "계좌를 선택합니다.",
      "Position·평가금액·실현/미실현 손익을 확인합니다.",
      "전략별 성과는 주문·체결 화면의 계좌 원장 집계와 함께 해석합니다.",
      "백테스트 성과와 섞지 않습니다.",
    ],
    buttons: ["새로고침", "계좌 선택"],
    normalState: ["잔고·포지션 숫자가 갱신됨"],
    errors: ["불일치 → 관리자 Recovery/Reconciliation 요청"],
    liveImpact: "조회만으로 주문이 나가지 않습니다.",
    nextSteps: ["내 리스크에서 한도를 점검합니다."],
  },
  {
    id: "user-risk",
    title: "8. 내 리스크",
    menuPath: "내 리스크",
    route: userRoutes.risk,
    status: "available",
    purpose:
      "사용자/계좌 리스크, 주문 한도, 손절·익절, 일 손실 한도, Kill Switch·Account Pause 영향을 이해합니다.",
    prerequisites: ["계좌 등록"],
    steps: [
      "사용자·계좌 리스크 설정을 확인·조정합니다.",
      "주문 한도·일 손실 한도·손절/익절 규칙을 점검합니다.",
      "Kill Switch ON이면 신규 주문이 차단됨을 이해합니다(해제는 관리자).",
      "Account Pause 시 해당 계좌 주문이 중단됩니다.",
    ],
    buttons: ["저장", "한도 수정"],
    normalState: ["한도 내 주문만 허용"],
    errors: ["한도 초과 거절 → 수량/한도 재설정"],
    liveImpact: "리스크 설정은 LIVE에서도 주문을 막을 수 있습니다. 해제 권한은 관리자입니다.",
    nextSteps: ["리포트에서 성과를 점검합니다."],
  },
  {
    id: "user-reports",
    title: "9. 내 리포트",
    menuPath: "내 리포트",
    route: userRoutes.reports,
    status: "available",
    purpose: "백테스트 성과와 Paper/실거래(계좌) 성과를 구분해 확인합니다.",
    prerequisites: ["백테스트 실행 또는 계좌 체결 이력"],
    steps: [
      "백테스트 성과는 시뮬레이션 결과임을 확인합니다.",
      "Paper/실거래 성과는 계좌 원장 기준임을 확인합니다.",
      "두 지표를 동일 전략이라도 직접 합산하지 않습니다.",
    ],
    buttons: ["리포트 조회", "기간 필터"],
    normalState: ["출처(백테스트 vs 계좌)가 표시됨"],
    errors: ["데이터 없음 → 선행 실행/체결 확인"],
    liveImpact: "리포트 조회는 주문에 영향 없습니다.",
    nextSteps: ["알림·설정에서 보안을 점검합니다."],
  },
  {
    id: "user-settings",
    title: "10. 알림 및 설정",
    menuPath: "알림 / 내 정보 → 프로필·설정",
    route: userRoutes.settings,
    status: "available",
    purpose: "Telegram 알림, 비밀번호, Credential 보안을 관리합니다.",
    prerequisites: ["로그인"],
    steps: [
      "`알림`에서 수신 설정을 확인합니다.",
      "`설정`/`프로필`에서 비밀번호를 변경합니다.",
      "Credential은 마스킹된 상태만 확인하고 Secret을 화면에 재출력하지 않습니다.",
    ],
    buttons: ["비밀번호 변경", "알림 설정 저장"],
    normalState: ["설정 저장 성공 메시지"],
    errors: ["알림 미수신 → Telegram 연동은 관리자 화면에서 점검"],
    liveImpact: "설정 변경만으로 주문이 발생하지 않습니다.",
    nextSteps: ["자동매매 시작 순서 탭을 참고합니다."],
  },
];
