"""UPBIT entry→order execution trace — OBSERVABILITY ONLY."""

from __future__ import annotations

from datetime import datetime, timezone

# Deployment 이후 PROVEN lineage 시작 시각 (migration/첫 trace row 기준 갱신)
TRACE_COVERAGE_START_AT: datetime | None = None

CHANGE_CODE = "UPBIT_ENTRY_SIGNAL_EMIT_DEDUP_RELIABILITY_FIX"
CHANGE_CLASSIFICATION = "RELIABILITY_BUG_FIX"  # NOT_STRATEGY_POLICY_CHANGE

# Append-only stage names (canonical)
STAGE_ENTRY_PASS = "ENTRY_PASS"
STAGE_SIGNAL_EMIT_ATTEMPT = "SIGNAL_EMIT_ATTEMPT"
STAGE_SIGNAL_EMITTED = "SIGNAL_EMITTED"
STAGE_SIGNAL_SUPPRESSED = "SIGNAL_SUPPRESSED"
STAGE_EXECUTOR_RECEIVED = "EXECUTOR_RECEIVED"
STAGE_EXECUTOR_REJECTED = "EXECUTOR_REJECTED"
STAGE_BEGIN_ENTRY_ATTEMPT = "BEGIN_ENTRY_ATTEMPT"
STAGE_BEGIN_ENTRY_ACCEPTED = "BEGIN_ENTRY_ACCEPTED"
STAGE_BEGIN_ENTRY_REJECTED = "BEGIN_ENTRY_REJECTED"
STAGE_ADMISSION_ATTEMPT = "ADMISSION_ATTEMPT"
STAGE_ADMISSION_ACCEPTED = "ADMISSION_ACCEPTED"
STAGE_ADMISSION_REJECTED = "ADMISSION_REJECTED"
STAGE_ORDER_INTENT_CREATED = "ORDER_INTENT_CREATED"
STAGE_ORDER_PERSISTED = "ORDER_PERSISTED"
STAGE_OUTBOX_ENQUEUED = "OUTBOX_ENQUEUED"
STAGE_BROKER_SUBMITTED = "BROKER_SUBMITTED"
STAGE_BROKER_ACCEPTED = "BROKER_ACCEPTED"
STAGE_BROKER_REJECTED = "BROKER_REJECTED"
STAGE_BUY_PARTIAL_FILL = "BUY_PARTIAL_FILL"
STAGE_BUY_FILLED = "BUY_FILLED"

DECISION_PASS = "PASS"
DECISION_ACCEPT = "ACCEPT"
DECISION_REJECT = "REJECT"
DECISION_SKIP = "SKIP"
DECISION_FAIL = "FAIL"

LIFECYCLE_INITIAL = "INITIAL"
LIFECYCLE_REVALIDATION = "REVALIDATION"

# Infrastructure failures — Data Trust / incident 대상 (policy reject 제외)
INFRASTRUCTURE_FAILURE_REASONS = frozenset(
    {
        "ORDER_PERSIST_FAILED",
        "ORDER_OUTBOX_ENQUEUE_FAILED",
        "BROKER_SUBMIT_FAILED",
        "SYSTEM_EXECUTOR_FAILURE",
        "BROKER_DIVERGENCE",
        "AUTOTRADING_TRACE_PERSIST_FAILED",
        "FULL_MARKET_GATE_FAILED",
    }
)

TERMINAL_REJECT_STAGES = frozenset(
    {
        STAGE_SIGNAL_SUPPRESSED,
        STAGE_EXECUTOR_REJECTED,
        STAGE_BEGIN_ENTRY_REJECTED,
        STAGE_ADMISSION_REJECTED,
        STAGE_BROKER_REJECTED,
    }
)


def utc_now() -> datetime:
    return datetime.now(timezone.utc)
