"""Exit Optimization Shadow Lab V3 — research constants (REAL policy 불변)."""

from __future__ import annotations

from datetime import datetime, timezone

RULE_VERSION = "exit_optimization_shadow_v3"
LAB_ID = "EXIT_OPTIMIZATION_SHADOW_LAB_V3"
MARKET_UPBIT = "UPBIT"
RESEARCH_ONLY_LABEL = "RESEARCH_ONLY"

# Variant identity — V2 T* 와 충돌 없음
VARIANT_R0 = "R0"  # CURRENT_REAL baseline
VARIANT_E1 = "E1"  # FEE_AWARE_TRAILING
VARIANT_E2 = "E2"  # PEAK_PROFIT_TIERED_TRAILING
VARIANT_E3 = "E3"  # MA_CONFIRM_TRAILING
VARIANT_E4 = "E4"  # ANTI_CHURN_TRAILING

ALL_VARIANTS = (VARIANT_R0, VARIANT_E1, VARIANT_E2, VARIANT_E3, VARIANT_E4)
SHADOW_VARIANTS = (VARIANT_E1, VARIANT_E2, VARIANT_E3, VARIANT_E4)
LAB_COMPARE_VARIANTS = ALL_VARIANTS

POLICY_FEE_AWARE_TRAILING_V1 = "FEE_AWARE_TRAILING_V1"
POLICY_PEAK_TIERED_TRAILING_V1 = "PEAK_PROFIT_TIERED_TRAILING_V1"
POLICY_MA_CONFIRM_TRAILING_V1 = "MA_CONFIRM_TRAILING_V1"
POLICY_ANTI_CHURN_TRAILING_V1 = "ANTI_CHURN_TRAILING_V1"

STATUS_ACTIVE = "ACTIVE"
STATUS_DEFERRED = "DEFERRED"
STATUS_COMPLETED = "COMPLETED"
STATUS_CONTINUATION = "CONTINUATION"
STATUS_PRE_EXISTING_EXCLUDED = "PRE_EXISTING_POSITION_EXCLUDED"
STATUS_UNRESOLVED = "UNRESOLVED"
STATUS_INSUFFICIENT_MARKET_DATA = "INSUFFICIENT_MARKET_DATA"

# REAL mirror (UBA 1380 resolved — shadow 평가용, REAL 변경 없음)
REAL_STOP_LOSS_PCT = 3.0
REAL_TAKE_PROFIT_PCT = 2.0
REAL_TRAILING_ACTIVATION_PCT = 1.0
REAL_TRAILING_DRAWDOWN_PCT = 0.8
REAL_MAX_HOLD_SECONDS = 21600

# Promotion gates (N>=50이어도 auto promotion=false)
EARLY_REVIEW_N = 20
PRIMARY_REVIEW_N = 30
PROMOTION_REVIEW_N = 50
AUTO_PROMOTION = False

FEATURE_KEY = "upbit_exit_optimization_shadow_v3"
FEATURE_DEPLOY_EPOCH = datetime(2026, 9, 2, 7, 0, 0, tzinfo=timezone.utc)
FEATURE_DEPLOY_EPOCH_SOURCE = "wrk_20260902_exit_optimization_shadow_lab_v3"
