"""Entry Gate V2 Shadow — RESEARCH ONLY (LIVE E0 불변)."""

from __future__ import annotations

RULE_VERSION = "entry_gate_v2_shadow_v1"
MARKET = "UPBIT"
SOURCE_FORWARD = "V2_FORWARD"

V2_A = "V2_A"
V2_C = "V2_C"
V2_D = "V2_D"
ALL_V2_VARIANTS = (V2_A, V2_C, V2_D)

# Walk-forward median params (2026-09-10 research) — LIVE E0 thresholds NOT used
DEFAULT_SCORE_MIN = 0.525
DEFAULT_SCORE_MIN_BULL = 0.45
DEFAULT_SCORE_MIN_SIDE = 0.475
DEFAULT_MAX_GC_AGE_MIN = 20.0
DEFAULT_MAX_PRE5 = 0.10
DEFAULT_MAX_RANGE = 0.60

FEE_RT_PCT = 0.10
OUTCOME_WINDOWS_MIN = (5, 15, 30, 60)

STATUS_PENDING = "PENDING"
STATUS_COMPLETED = "COMPLETED"
STATUS_INSUFFICIENT = "INSUFFICIENT_OUTCOME"

LIVE_PROMOTION_ELIGIBLE = False
