"""Profitability Improvement Shadow Lab V1 — constants (REAL policy 불변)."""

from __future__ import annotations

from datetime import datetime, timezone

RULE_VERSION = "profitability_improvement_shadow_v1"
LAB_ID = "PROFITABILITY_IMPROVEMENT_SHADOW_LAB_V1"
MARKET_UPBIT = "UPBIT"
RESEARCH_ONLY_LABEL = "RESEARCH_ONLY"
AUTO_PROMOTION = False

# Lab A — Candidate Selection V2
LAB_A = "CANDIDATE_SELECTION_V2"
VARIANT_A0 = "A0"  # CURRENT_REAL_SCORE
VARIANT_A1 = "A1"  # MOMENTUM_QUALITY
VARIANT_A2 = "A2"  # RISK_ADJUSTED_MOMENTUM
VARIANT_A3 = "A3"  # TREND_CONFIRMATION
LAB_A_VARIANTS = (VARIANT_A0, VARIANT_A1, VARIANT_A2, VARIANT_A3)
LAB_A_LABELS = {
    VARIANT_A0: "CURRENT_REAL_SCORE",
    VARIANT_A1: "MOMENTUM_QUALITY",
    VARIANT_A2: "RISK_ADJUSTED_MOMENTUM",
    VARIANT_A3: "TREND_CONFIRMATION",
}
CANDIDATE_EARLY_REVIEW_N = 100
CANDIDATE_PRIMARY_REVIEW_N = 300
CANDIDATE_PROMOTION_REVIEW_N = 500

# Lab B — Exit Optimization V4 (V3와 별개 dimension)
LAB_B = "EXIT_OPTIMIZATION_V4"
VARIANT_B0 = "B0"  # CURRENT_REAL_EXIT
VARIANT_B1 = "B1"  # FEE_AWARE_PROFIT_LOCK
VARIANT_B2 = "B2"  # MFE_ADAPTIVE_TRAILING
VARIANT_B3 = "B3"  # MA_STATE_AWARE_TRAILING
LAB_B_VARIANTS = (VARIANT_B0, VARIANT_B1, VARIANT_B2, VARIANT_B3)
LAB_B_LABELS = {
    VARIANT_B0: "CURRENT_REAL_EXIT",
    VARIANT_B1: "FEE_AWARE_PROFIT_LOCK",
    VARIANT_B2: "MFE_ADAPTIVE_TRAILING",
    VARIANT_B3: "MA_STATE_AWARE_TRAILING",
}
EXIT_EARLY_REVIEW_N = 20
EXIT_PRIMARY_REVIEW_N = 30
EXIT_PROMOTION_REVIEW_N = 50

# Lab C — Reentry Anti-Churn
LAB_C = "REENTRY_ANTI_CHURN_V1"
VARIANT_C0 = "C0"  # CURRENT_REAL
VARIANT_C1 = "C1"  # COOLDOWN_60S
VARIANT_C2 = "C2"  # COOLDOWN_180S
VARIANT_C3 = "C3"  # CONTEXTUAL_REENTRY
LAB_C_VARIANTS = (VARIANT_C0, VARIANT_C1, VARIANT_C2, VARIANT_C3)
LAB_C_LABELS = {
    VARIANT_C0: "CURRENT_REAL",
    VARIANT_C1: "COOLDOWN_60S",
    VARIANT_C2: "COOLDOWN_180S",
    VARIANT_C3: "CONTEXTUAL_REENTRY",
}
REENTRY_EARLY_REVIEW_N = 20
REENTRY_PRIMARY_REVIEW_N = 30
REENTRY_PROMOTION_REVIEW_N = 50

# REAL mirror (shadow evaluation only)
REAL_STOP_LOSS_PCT = 3.0
REAL_TAKE_PROFIT_PCT = 2.0
REAL_TRAILING_ACTIVATION_PCT = 1.0
REAL_TRAILING_DRAWDOWN_PCT = 0.8
REAL_MAX_HOLD_SECONDS = 21600
ROUND_TRIP_FEE_PCT = 0.1  # Upbit taker ~0.05% * 2

# B1/B2 deterministic buckets (from 2026-09-02 distribution evidence)
B1_MIN_PROFIT_BUFFER_PCT = 0.15  # fee(0.1) + economic buffer
B2_MFE_MICRO_LT = 0.30  # below: widen trail (noise)
B2_MFE_LOCK_GTE = 1.00  # at/above: tighten profit lock
B2_TRAIL_MICRO = 1.50
B2_TRAIL_MID = 1.00
B2_TRAIL_LOCK = 0.60

STATUS_ACTIVE = "ACTIVE"
STATUS_COMPLETED = "COMPLETED"
STATUS_PENDING_OUTCOME = "PENDING_OUTCOME"
STATUS_PRE_EXISTING_EXCLUDED = "PRE_EXISTING_POSITION_EXCLUDED"
STATUS_INSUFFICIENT_DATA = "INSUFFICIENT_DATA"

FEATURE_KEY = "upbit_profitability_improvement_shadow"
FEATURE_DEPLOY_EPOCH = datetime(2026, 9, 3, 0, 0, 0, tzinfo=timezone.utc)
FEATURE_DEPLOY_EPOCH_SOURCE = "wrk_20260903_profitability_improvement_shadow_lab_v1"
