"""UPBIT Full-Market Dynamic LIVE — 모드·상태 상수."""

from __future__ import annotations

# 운영 모드 (계좌 assignment). 기본은 고정 심볼 보호.
MODE_FIXED_SYMBOL = "FIXED_SYMBOL"
# Legacy single full-market (기존 DB/API 호환)
MODE_FULL_MARKET_AUTO = "FULL_MARKET_AUTO"
MODE_FULL_MARKET_SINGLE = "FULL_MARKET_SINGLE"
MODE_FULL_MARKET_PORTFOLIO = "FULL_MARKET_PORTFOLIO"

FULL_MARKET_SINGLE_MODES = frozenset(
    {MODE_FULL_MARKET_AUTO, MODE_FULL_MARKET_SINGLE}
)
FULL_MARKET_ANY_MODES = frozenset(
    {
        MODE_FULL_MARKET_AUTO,
        MODE_FULL_MARKET_SINGLE,
        MODE_FULL_MARKET_PORTFOLIO,
    }
)


def is_full_market_single(mode: str | None) -> bool:
    return str(mode or "").upper() in FULL_MARKET_SINGLE_MODES


def is_full_market_portfolio(mode: str | None) -> bool:
    return str(mode or "").upper() == MODE_FULL_MARKET_PORTFOLIO


def is_any_full_market(mode: str | None) -> bool:
    return str(mode or "").upper() in FULL_MARKET_ANY_MODES


# Symbol switch state machine (SINGLE)
STATE_IDLE = "IDLE"
STATE_CANDIDATE_SELECTED = "CANDIDATE_SELECTED"
STATE_SWITCH_PRECHECK = "SWITCH_PRECHECK"
STATE_SWITCHED = "SWITCHED"
STATE_WARMUP = "WARMUP"
STATE_POSITION_OPEN = "POSITION_OPEN"
STATE_EXIT_PENDING = "EXIT_PENDING"
STATE_POSITION_CLOSED = "POSITION_CLOSED"
STATE_COOLDOWN = "COOLDOWN"
STATE_BLOCKED = "BLOCKED"

# Portfolio entry state (assignment-level)
PORTFOLIO_ENTRY_RUNNING = "RUNNING"
PORTFOLIO_ENTRY_PAUSED = "ENTRY_PAUSED"
PORTFOLIO_ENTRY_BLOCKED = "BLOCKED"

# Position slot status
SLOT_EMPTY = "EMPTY"
SLOT_SELECTED = "SELECTED"
SLOT_WARMING_UP = "WARMING_UP"
SLOT_WAITING_SIGNAL = "WAITING_SIGNAL"
SLOT_RESERVED = "RESERVED"
SLOT_ENTRY_PENDING = "ENTRY_PENDING"
SLOT_OPEN = "OPEN"
SLOT_EXIT_PENDING = "EXIT_PENDING"
SLOT_COOLDOWN = "COOLDOWN"
SLOT_BLOCKED = "BLOCKED"

# Runtime/Hub에 구독해야 하는 심볼 (자금 reservation 전 포함)
SLOT_RUNTIME_SYMBOL_STATUSES = frozenset(
    {
        SLOT_SELECTED,
        SLOT_WARMING_UP,
        SLOT_WAITING_SIGNAL,
        SLOT_RESERVED,
        SLOT_ENTRY_PENDING,
        SLOT_OPEN,
        SLOT_EXIT_PENDING,
    }
)

# 활성 심볼 유니크 인덱스 / 노출 집계
SLOT_ACTIVE_SYMBOL_STATUSES = frozenset(
    {
        SLOT_SELECTED,
        SLOT_WARMING_UP,
        SLOT_WAITING_SIGNAL,
        SLOT_RESERVED,
        SLOT_ENTRY_PENDING,
        SLOT_OPEN,
        SLOT_EXIT_PENDING,
    }
)

# 주문 직전 capital lock
SLOT_RESERVED_STATUSES = frozenset(
    {
        SLOT_RESERVED,
        SLOT_ENTRY_PENDING,
    }
)

# Scanner가 hold 중 교체하면 안 되는 후보 대기 상태
SLOT_CANDIDATE_HOLD_STATUSES = frozenset(
    {
        SLOT_SELECTED,
        SLOT_WARMING_UP,
        SLOT_WAITING_SIGNAL,
    }
)

# AI LIVE Gate (assignment scoped — global true 금지)
AI_GATE_OFF = "OFF"
AI_GATE_SHADOW = "SHADOW"
AI_GATE_ENFORCE = "ENFORCE"

# Candidate selection provenance
SOURCE_UPBIT_OPPORTUNITY_SCANNER = "UPBIT_OPPORTUNITY_SCANNER"

SELECTION_STATUS_SELECTED = "SELECTED"
SELECTION_STATUS_ACTIVE = "ACTIVE"
SELECTION_STATUS_CLOSED = "CLOSED"
SELECTION_STATUS_REJECTED = "REJECTED"
SELECTION_STATUS_SUPERSEDED = "SUPERSEDED"

# Strategy-owned position binding
BINDING_STATUS_OPEN = "OPEN"
BINDING_STATUS_EXIT_PENDING = "EXIT_PENDING"
BINDING_STATUS_CLOSED = "CLOSED"

# Admin confirm phrases
CONFIRM_ENABLE_FULL_MARKET = "전체시장 자동선정 모드 시작"
CONFIRM_DISABLE_FULL_MARKET = "전체시장 자동선정 모드 중지"
CONFIRM_ENABLE_PORTFOLIO = "전체시장 포트폴리오 모드 시작"
CONFIRM_DISABLE_PORTFOLIO = "전체시장 포트폴리오 모드 중지"
# ENTRY_PENDING + entry_order_id null 고착 해제 (주문/히스토리 삭제 아님)
CONFIRM_RECOVER_STALE_ENTRY_PENDING = (
    "CONFIRM_RECOVER_STALE_ENTRY_PENDING"
)
CONFIRM_ALIGN_PORTFOLIO_ENTRY_PIPELINE = (
    "CONFIRM_ALIGN_PORTFOLIO_ENTRY_PIPELINE"
)

ALLOW_RECOMMENDATIONS = frozenset({"ALLOW", "REDUCE"})
BLOCK_RECOMMENDATIONS = frozenset({"BLOCK", "REJECT"})

# Portfolio conservative defaults (Enable 시 시드)
DEFAULT_MAX_POSITIONS = 3
DEFAULT_PER_POSITION_TARGET_PCT = 0.08
DEFAULT_MAX_SYMBOL_EXPOSURE_PCT = 0.12
DEFAULT_MAX_TOTAL_EXPOSURE_PCT = 0.30
DEFAULT_MIN_CASH_RESERVE_PCT = 0.60
DEFAULT_DAILY_LOSS_LIMIT_PCT = 0.02
DEFAULT_CONSECUTIVE_LOSS_LIMIT = 3
DEFAULT_ENTRY_COOLDOWN_SECONDS = 300
DEFAULT_CANDIDATE_MAX_AGE_SECONDS = 1800
DEFAULT_PORTFOLIO_MAX_PENDING_ENTRIES = 1
# UPBIT_SHORT_TERM_OPERATION_V1 — REAL AUTO ENTRY 일일 한도 (SELL 미포함)
UPBIT_SHORT_TERM_DAILY_ENTRY_LIMIT = 6
DEFAULT_PORTFOLIO_DAILY_ENTRY_LIMIT = UPBIT_SHORT_TERM_DAILY_ENTRY_LIMIT
# Live safety / admission 표시용 canonical reason
REASON_DAILY_ENTRY_LIMIT_REACHED = "DAILY_ENTRY_LIMIT_REACHED"
# WAITING_SIGNAL 후보 hold / 교체 임계 (초·점수)
DEFAULT_PORTFOLIO_CANDIDATE_HOLD_SECONDS = 1800
DEFAULT_PORTFOLIO_CANDIDATE_SWITCH_MIN_SCORE_DELTA = 8.0
# WAITING_SIGNAL 최대 대기 (hold 이후 max-wait/stale 교체)
DEFAULT_PORTFOLIO_CANDIDATE_MAX_WAIT_SECONDS = 10800
# ENTRY_PENDING(실제 주문 단계) timeout
DEFAULT_PORTFOLIO_ENTRY_PENDING_TIMEOUT_SECONDS = 120.0
