"""UPBIT Full-Market Dynamic LIVE — 모드·상태 상수."""

from __future__ import annotations

# 운영 모드 (계좌 assignment). 기본은 고정 심볼 보호.
MODE_FIXED_SYMBOL = "FIXED_SYMBOL"
MODE_FULL_MARKET_AUTO = "FULL_MARKET_AUTO"

# Symbol switch state machine
STATE_IDLE = "IDLE"
STATE_CANDIDATE_SELECTED = "CANDIDATE_SELECTED"
STATE_SWITCH_PRECHECK = "SWITCH_PRECHECK"
STATE_SWITCHED = "SWITCHED"
STATE_WARMUP = "WARMUP"
STATE_POSITION_OPEN = "POSITION_OPEN"
STATE_EXIT_PENDING = "EXIT_PENDING"
STATE_POSITION_CLOSED = "POSITION_CLOSED"
STATE_COOLDOWN = "COOLDOWN"
STATE_BLOCKED = "BLOCKED"

# AI LIVE Gate (assignment scoped — global true 금지)
AI_GATE_OFF = "OFF"
AI_GATE_SHADOW = "SHADOW"
AI_GATE_ENFORCE = "ENFORCE"

# Candidate selection provenance
SOURCE_UPBIT_OPPORTUNITY_SCANNER = "UPBIT_OPPORTUNITY_SCANNER"

SELECTION_STATUS_SELECTED = "SELECTED"
SELECTION_STATUS_ACTIVE = "ACTIVE"
SELECTION_STATUS_CLOSED = "CLOSED"
SELECTION_STATUS_REJECTED = "REJECTED"
SELECTION_STATUS_SUPERSEDED = "SUPERSEDED"

# Strategy-owned position binding
BINDING_STATUS_OPEN = "OPEN"
BINDING_STATUS_EXIT_PENDING = "EXIT_PENDING"
BINDING_STATUS_CLOSED = "CLOSED"

# Admin confirm phrases
CONFIRM_ENABLE_FULL_MARKET = "전체시장 자동선정 모드 시작"
CONFIRM_DISABLE_FULL_MARKET = "전체시장 자동선정 모드 중지"

ALLOW_RECOMMENDATIONS = frozenset({"ALLOW", "REDUCE"})
BLOCK_RECOMMENDATIONS = frozenset({"BLOCK", "REJECT"})
