/** STEP 8-11A — Operations Dashboard display labels (UTF-8). */
export const OPS_DASHBOARD_LABELS = {
  pageTitle: '거래 운영 현황',
  pageDescription:
    '조회 전용 거래 운영 대시보드. Runtime·주문·리스크 요약만 표시하며 LIVE/ARM/Runtime 제어는 하지 않습니다.',
  lastChecked: '마지막 점검',
  autoOff: '자동 끔',
  refresh: '수동 새로고침',
  accountsLink: '계좌 관리',
  readOnlyBanner:
    '조회 전용입니다. Runtime 제어는 자동매매 Runtime, LIVE/ARM은 업비트 계좌, Preflight·리스크·복구는 각 canonical 화면에서 수행합니다. 시스템 health 상세는 시스템 모니터링을 사용하세요.',
  overviewFailed: '개요 조회 실패 — 이전 데이터 유지',
  tabOverview: '개요',
  tabAccounts: '계좌 준비 상태',
  tabOrders: '주문·체결',
  tabRisk: '리스크',
  tabSchedulers: '스케줄러·런타임',
  tabPositions: '포지션',
  tabAlerts: '경고·수동 검토',
  tabAudit: '감사·알림',
  tabAuditSub: '감사',
  tabNotificationSub: '알림',
  overall: '전체 상태',
  database: '데이터베이스',
  tradingScheduler: '거래 스케줄러',
  trackingScheduler: '추적 스케줄러',
  postFillScheduler: 'Post-fill 스케줄러',
  recoveryScheduler: '복구 스케줄러',
  runtime: '런타임',
  killSwitch: '긴급 중지(Kill Switch)',
  criticalAlerts: '긴급 경고',
  manualReview: '수동 검토',
  orderableKrw: '주문 가능 원화',
  lockedKrw: '잠금 원화',
  dailyLoss: '일일 손실',
  remainingCapacity: '남은 손실 한도',
  dryRunReady: '모의 실행 준비',
  liveExecutionReady: '실주문 준비',
  blockers: '차단 사유',
  status: '상태',
  noAccounts: '계좌 없음',
  owner: '소유자',
  broker: '거래소/증권사',
  credential: '자격증명',
} as const;
