"""공통 Symbol Ownership 상수 — KIWOOM/UPBIT 동일 계약."""

from __future__ import annotations

# 논리 ownership (UI: 일반매매/자동매매)
OWNER_MANUAL = "MANUAL"
OWNER_AUTO = "AUTO"
OWNER_FREE = "FREE"
OWNER_UNKNOWN = "UNKNOWN"
OWNER_AUTO_EXCLUDED = "AUTO_EXCLUDED"  # 사용자 명시 제외 (보유와 별개)

# reason codes
REASON_MANUAL_POSITION = "MANUAL_POSITION"
REASON_MANUAL_OPEN_ORDER = "MANUAL_OPEN_ORDER"
REASON_AUTO_BINDING = "AUTO_BINDING"
REASON_AUTO_OPEN_ORDER = "AUTO_OPEN_ORDER"
REASON_AUTO_SLOT = "AUTO_SLOT"
REASON_USER_EXCLUDED = "AUTO_EXCLUDED_BY_USER"
REASON_SAME_SYMBOL_MIX = "SAME_SYMBOL_MANUAL_AUTO_MIX"
REASON_UNKNOWN_PROVENANCE = "SYMBOL_OWNERSHIP_UNKNOWN"

# entry skip / telemetry
SKIP_MANUAL_SYMBOL_EXCLUDED = "MANUAL_SYMBOL_EXCLUDED"
SKIP_AUTO_ALREADY_MANAGED = "AUTO_SYMBOL_ALREADY_MANAGED"
SKIP_OWNERSHIP_UNKNOWN = "SYMBOL_OWNERSHIP_UNKNOWN"
SKIP_AUTO_EXCLUDED = "AUTO_EXCLUDED_BY_USER"
SKIP_SYMBOL_HOLD = "SYMBOL_OWNERSHIP_HOLD"

# conflict
CONFLICT_SAME_SYMBOL_MANUAL_AUTO = "SAME_SYMBOL_MANUAL_AUTO_CONFLICT"
CONFLICT_REMOTE_MANUAL_ACTIVITY = "REMOTE_MANUAL_ACTIVITY"
CONFLICT_REMOTE_AUTO_MISMATCH = "REMOTE_AUTO_PROVENANCE_MISMATCH"

OPEN_ORDER_STATUSES = frozenset(
    {
        "CREATED",
        "PENDING",
        "SUBMITTING",
        "SENT",
        "ACCEPTED",
        "PARTIALLY_FILLED",
        "REMOTE_LOOKUP_PENDING",
        "CANCEL_REQUESTED",
        "REPLACE_REQUESTED",
    }
)

ACTIVE_SLOT_STATUSES = frozenset(
    {
        "WAITING_SIGNAL",
        "ENTRY_PENDING",
        "OPEN",
        "EXIT_PENDING",
        "COOLDOWN",
    }
)

# ENTRY 차단용 — WAITING_SIGNAL/ENTRY_PENDING(자기 진행)은 제외.
# WAITING만으로 AUTO_SYMBOL_ALREADY_MANAGED 를 내면
# begin→live_safety→rollback 루프 + Telegram 폭주가 난다.
ENTRY_OCCUPYING_SLOT_STATUSES = frozenset(
    {
        "OPEN",
        "EXIT_PENDING",
        "COOLDOWN",
    }
)
