"""UPBIT Churn Guard Shadow V1 — RESEARCH/OBSERVABILITY ONLY.

REAL entry/exit/Kill/LIVE/ARM 무영향. Shadow 실패 = fail-open toward trading.
"""

from __future__ import annotations

CHURN_GUARD_VERSION = "churn_guard_shadow_v1"
MODE = "SHADOW"
REAL_BLOCK_ENABLED = False
FAMILY = "UPBIT_CHURN_GUARD_SHADOW_V1"

# Detection profiles (동시 평가, REAL gate 아님)
PROFILE_RAPID_REENTRY = "RAPID_REENTRY"
PROFILE_REPEATED_LOSS = "REPEATED_LOSS"
PROFILE_SAME_EXIT_LOOP = "SAME_EXIT_LOOP"
PROFILE_FEE_CHURN = "FEE_CHURN"
PROFILE_MICRO_TICK_CHURN = "MICRO_TICK_CHURN"
PROFILE_COMPOSITE_CHURN = "COMPOSITE_CHURN"

DETECTION_PROFILES = (
    PROFILE_RAPID_REENTRY,
    PROFILE_REPEATED_LOSS,
    PROFILE_SAME_EXIT_LOOP,
    PROFILE_FEE_CHURN,
    PROFILE_MICRO_TICK_CHURN,
    PROFILE_COMPOSITE_CHURN,
)

# Threshold variants — WOULD_ALERT / NO_ALERT only
VARIANT_S0 = "S0"
VARIANT_S1 = "S1"
VARIANT_S2 = "S2"
VARIANT_S3 = "S3"
THRESHOLD_VARIANTS = (VARIANT_S0, VARIANT_S1, VARIANT_S2, VARIANT_S3)

# Severity (shadow only — Kill Switch 미연동)
SEVERITY_INFO = "INFO"
SEVERITY_WARNING = "WARNING"
SEVERITY_CRITICAL = "CRITICAL"
SEVERITY_RANK = {
    SEVERITY_INFO: 1,
    SEVERITY_WARNING: 2,
    SEVERITY_CRITICAL: 3,
}

# Classifications
CLS_RAPID_REENTRY_CHURN = "RAPID_REENTRY_CHURN"
CLS_MA_DEAD_CROSS_REENTRY_CHURN = "MA_DEAD_CROSS_REENTRY_CHURN"
CLS_TRAILING_STOP_REENTRY_CHURN = "TRAILING_STOP_REENTRY_CHURN"
CLS_REPEATED_LOSS_CHURN = "REPEATED_LOSS_CHURN"
CLS_FEE_DOMINATED_CHURN = "FEE_DOMINATED_CHURN"
CLS_MICRO_TICK_CHURN = "MICRO_TICK_CHURN"
CLS_CANDIDATE_DOMINANCE_CHURN = "CANDIDATE_DOMINANCE_CHURN"
CLS_ORDER_LIFECYCLE_ANOMALY = "ORDER_LIFECYCLE_ANOMALY"
CLS_COMPOSITE_CHURN = "COMPOSITE_CHURN"
CLS_UNKNOWN = "UNKNOWN"

CLASSIFICATION_LABEL_KO = {
    CLS_RAPID_REENTRY_CHURN: "빠른 재진입 반복",
    CLS_MA_DEAD_CROSS_REENTRY_CHURN: "MA 데드크로스 반복 재진입",
    CLS_TRAILING_STOP_REENTRY_CHURN: "트레일링 스탑 반복 재진입",
    CLS_REPEATED_LOSS_CHURN: "연속 손실 반복매매",
    CLS_FEE_DOMINATED_CHURN: "수수료 주도 손실",
    CLS_MICRO_TICK_CHURN: "미세 가격차 반복 손실",
    CLS_CANDIDATE_DOMINANCE_CHURN: "후보 독점 재선택",
    CLS_ORDER_LIFECYCLE_ANOMALY: "주문 수명주기 이상(겹침 진입)",
    CLS_COMPOSITE_CHURN: "복합 반복매매 패턴",
    CLS_UNKNOWN: "원인 미확정",
}

SEVERITY_LABEL_KO = {
    SEVERITY_INFO: "정보",
    SEVERITY_WARNING: "경고",
    SEVERITY_CRITICAL: "심각",
}

STATUS_ACTIVE = "ACTIVE"
STATUS_RESOLVED = "RESOLVED"

# Observability hysteresis (NOT REAL entry cooldown)
RESOLVE_IDLE_SECONDS = 1800  # 30m without new losing evidence
RESOLVE_MIN_WINNING_RTS = 2
REALERT_MIN_SECONDS = 600  # 10m
REALERT_NET_LOSS_DELTA_KRW = 100.0
LOOKBACK_CLOSED_RTS = 12
LOOKBACK_SECONDS = 7200  # 2h feature window

OWNERSHIP_STRATEGY = "STRATEGY_OWNED"
OWNERSHIP_MANUAL = "MANUAL"
OWNERSHIP_UNKNOWN = "UNKNOWN"
OWNERSHIP_AMBIGUOUS = "AMBIGUOUS"

COUNTERFACTUAL_PAUSE_KEYS = (
    "IF_SYMBOL_ENTRY_PAUSED_15M",
    "IF_SYMBOL_ENTRY_PAUSED_30M",
    "IF_SYMBOL_ENTRY_PAUSED_60M",
)
COUNTERFACTUAL_PAUSE_SECONDS = {
    "IF_SYMBOL_ENTRY_PAUSED_15M": 15 * 60,
    "IF_SYMBOL_ENTRY_PAUSED_30M": 30 * 60,
    "IF_SYMBOL_ENTRY_PAUSED_60M": 60 * 60,
}

EVENT_TYPE_TELEGRAM = "UPBIT_CHURN_GUARD_SHADOW"
