export const queryKeys = {
  auth: {
    all: ["auth"] as const,
    me: () => ["auth", "me"] as const,
  },
  system: {
    all: ["system"] as const,
    status: () => ["system", "status"] as const,
    health: () => ["system", "health"] as const,
    dashboard: (params?: object) => ["system", "dashboard", params ?? {}] as const,
  },
  dashboard: {
    all: ["dashboard"] as const,
    summary: () => ["dashboard", "summary"] as const,
  },
  user: {
    brokerAccount: () => ["user", "broker-account"] as const,
    kiwoomConfig: () => ["user", "kiwoom-config"] as const,
    paperPositions: (id: number) => ["user", "paper-positions", id] as const,
    realtimeStrategy: () => ["user", "realtime-strategy"] as const,
    realtimeExecution: () => ["user", "realtime-execution"] as const,
    killSwitch: () => ["user", "kill-switch"] as const,
    strategyRuntime: () => ["user", "strategy-runtime"] as const,
    activeDeployment: () => ["user", "active-deployment"] as const,
    strategyRanking: () => ["user", "strategy-ranking"] as const,
    strategySelection: () => ["user", "strategy-selection"] as const,
    backtestRuns: () => ["user", "backtest-runs"] as const,
    portfolioSummary: () => ["user", "portfolio-summary"] as const,
    positions: () => ["user", "positions"] as const,
    orders: () => ["user", "orders"] as const,
    executions: () => ["user", "executions"] as const,
    paperOrders: () => ["user", "paper-orders"] as const,
    topCandidates: (ex: string) => ["user", "top-candidates", ex] as const,
    aiLatest: (ex: string) => ["user", "ai-latest", ex] as const,
    aiRuns: () => ["user", "ai-runs"] as const,
    news: (ex: string, sym: string) => ["user", "news", ex, sym] as const,
    notificationStatus: () => ["user", "notification-status"] as const,
  },
};
