# -*- coding: utf-8 -*-
"""CONTROLLED_AUTO_RESIDUAL_CLEANUP — 상수 / 아키텍처 불변식."""

from __future__ import annotations

from decimal import Decimal

# 경로 식별자 — 일반 AUTO exit supervisor / slot 과 분리
CLEANUP_PATH = "CONTROLLED_AUTO_RESIDUAL_CLEANUP"

# provenance kind (meta_json.auto_residual_truth.kind)
KIND_SELLABLE_CURRENT = "SELLABLE_CURRENT_AUTO_RESIDUAL"
KIND_CURRENT_RESIDUAL = "CURRENT_AUTO_RESIDUAL"
KIND_CURRENT_DUST = "CURRENT_AUTO_DUST"
KIND_HISTORICAL_ONLY = "HISTORICAL_ONLY_RESIDUAL"
KIND_PROVENANCE_AMBIGUOUS = "PROVENANCE_AMBIGUOUS"

ALLOWED_CLEANUP_KINDS = frozenset(
    {
        KIND_SELLABLE_CURRENT,
        KIND_CURRENT_RESIDUAL,
        KIND_CURRENT_DUST,
    }
)
BLOCKED_CLEANUP_KINDS = frozenset(
    {
        KIND_HISTORICAL_ONLY,
        KIND_PROVENANCE_AMBIGUOUS,
    }
)

# UBA1380 수동 보유 — cleanup 대상 절대 금지
MANUAL_PROTECTED_CURRENCIES = frozenset({"BTC", "ETH", "DOGE", "SKY"})

# 요청 lifecycle (이번 단계는 PREPARED/DRY-RUN 중심)
STATUS_PREPARED = "PREPARED"
STATUS_APPROVED = "APPROVED"
STATUS_SUBMITTED = "SUBMITTED"
STATUS_AMBIGUOUS = "AMBIGUOUS"
STATUS_PARTIAL_FILLED = "PARTIAL_FILLED"
STATUS_FILLED = "FILLED"
STATUS_FAILED = "FAILED"

# 재주문 차단 상태
BLOCKING_REQUEST_STATUSES = frozenset(
    {
        STATUS_SUBMITTED,
        "PENDING",
        STATUS_FILLED,
        STATUS_AMBIGUOUS,
        STATUS_PARTIAL_FILLED,
        STATUS_APPROVED,
    }
)

OWNERSHIP_CONFIDENCE_HIGH = "HIGH"

REASON_HISTORICAL_ONLY_BLOCKED = "HISTORICAL_ONLY_RESIDUAL_BLOCKED"
REASON_BELOW_MIN_NOTIONAL = "NOT_ELIGIBLE_BELOW_MIN_NOTIONAL"
REASON_UNSELLABLE_AUTO_DUST = "UNSELLABLE_AUTO_DUST"
REASON_MANUAL_PROTECTED = "MANUAL_PROTECTED_SYMBOL"
REASON_MANUAL_CONTAMINATION = "MANUAL_CONTAMINATION"
REASON_KILL_SWITCH = "KILL_SWITCH_ACTIVE"
REASON_AMBIGUOUS_ORDER = "AMBIGUOUS_ORDER_PRESENT"
REASON_UNRESOLVED_EXIT = "UNRESOLVED_EXIT_PRESENT"
REASON_RECOVERY_CONFLICT = "RECOVERY_CONFLICT_PRESENT"
REASON_OPEN_SELL_CONFLICT = "EXISTING_OPEN_SELL_CONFLICT"
REASON_ALREADY_CLEANED = "RESIDUAL_ALREADY_CLEANED"
REASON_IDEMPOTENCY_BLOCK = "EXISTING_CLEANUP_REQUEST_BLOCK"
REASON_BROKER_QTY_ZERO = "BROKER_QTY_ZERO"
REASON_PROVENANCE_QTY_ZERO = "PROVENANCE_QTY_ZERO"
REASON_NO_MARK_PRICE = "MARK_PRICE_MISSING"
REASON_UBA_MISMATCH = "UBA_NOT_ALLOWED"
REASON_BROKER_MISMATCH = "BROKER_NOT_UPBIT"
REASON_ACCOUNT_NOT_READY = "BROKER_ACCOUNT_NOT_READY"
REASON_CREDENTIAL_NOT_READY = "CREDENTIAL_NOT_READY"
REASON_OWNERSHIP_CONFIDENCE = "OWNERSHIP_CONFIDENCE_NOT_HIGH"
REASON_APPROVAL_REQUIRED = "EXPLICIT_APPROVAL_REQUIRED"
REASON_BROKER_SUBMIT_DISABLED = "BROKER_SUBMIT_DISABLED"
REASON_QTY_EXCEEDS_ATTRIBUTABLE = "QTY_EXCEEDS_ATTRIBUTABLE"

ZERO = Decimal("0")
QTY_STEP = Decimal("0.00000001")

# 아키텍처 불변식 — 문서/증거/테스트 SoT
ARCHITECTURE = {
    "path": CLEANUP_PATH,
    "closed_binding_reopened": False,
    "uses_auto_slot": False,
    "uses_candidate_slot": False,
    "uses_normal_exit_supervisor": False,
    "requires_explicit_approval": True,
    "unattended_auto_submit": False,
    "binding_status_mutation": False,
    "owned_quantity_mutation": False,
}
