"""KIWOOM Entry Signal Shadow — constants (RESEARCH_ONLY)."""

from __future__ import annotations

RULE_VERSION = "kiwoom_entry_signal_shadow_v1"
MARKET = "KIWOOM"
RESEARCH_ONLY_LABEL = "RESEARCH_ONLY_NO_REAL_ORDER"

VARIANT_K0 = "K0"
ALL_VARIANTS = (VARIANT_K0,)

STATUS_PENDING = "PENDING"
STATUS_COMPLETED = "COMPLETED"
STATUS_INSUFFICIENT_OUTCOME = "INSUFFICIENT_OUTCOME"

HORIZON_PENDING = "PENDING"
HORIZON_MATURED = "MATURED"
HORIZON_MISSING_DATA = "MISSING_DATA"

# minute windows — 24h = calendar elapsed (KRX minute candles, 비거래시간 MISSING)
OUTCOME_WINDOWS_MIN = (5, 15, 30, 60, 240, 1440)
KIWOOM_24H_SEMANTICS = "CALENDAR_ELAPSED_24H_MINUTE_CANDLES"

KIWOOM_SAMPLE_IDENTITY = "research_opportunity_id"
ENTRY_EVENT_GOLDEN_CROSS = "K0_ENTRY_OPPORTUNITY"

SOURCE_FORWARD = "FORWARD_NATURAL"

FORWARD_SAMPLE_TARGET = 50
