"""STEP 8-5-7 — KRX Trading Calendar 공통 상수."""

from __future__ import annotations

from enum import StrEnum


class CalendarVerifiedStatus(StrEnum):
    VERIFIED = "VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    STALE = "STALE"
    MISSING = "MISSING"
    CONFLICT = "CONFLICT"


class CalendarSessionType(StrEnum):
    CLOSED = "CLOSED"
    REGULAR = "REGULAR"
    DELAYED_OPEN = "DELAYED_OPEN"
    EARLY_CLOSE = "EARLY_CLOSE"
    SPECIAL_SESSION = "SPECIAL_SESSION"


class CalendarReasonCode(StrEnum):
    ALWAYS_OPEN = "ALWAYS_OPEN"
    CALENDAR_OPEN = "CALENDAR_OPEN"
    CALENDAR_CLOSED = "CALENDAR_CLOSED"
    WEEKEND = "WEEKEND"
    WEEKDAY_FALLBACK = "WEEKDAY_FALLBACK"
    CALENDAR_MISSING = "CALENDAR_MISSING"
    CALENDAR_UNVERIFIED = "CALENDAR_UNVERIFIED"
    CALENDAR_STALE = "CALENDAR_STALE"
    CALENDAR_CONFLICT = "CALENDAR_CONFLICT"
    CALENDAR_UNAVAILABLE = "CALENDAR_UNAVAILABLE"


# LIVE Fail Closed — 거래일로 취급하지 않음
CALENDAR_UNAVAILABLE_REASONS = frozenset(
    {
        CalendarReasonCode.CALENDAR_MISSING.value,
        CalendarReasonCode.CALENDAR_UNVERIFIED.value,
        CalendarReasonCode.CALENDAR_STALE.value,
        CalendarReasonCode.CALENDAR_CONFLICT.value,
        CalendarReasonCode.CALENDAR_UNAVAILABLE.value,
    }
)

KRX_TIMEZONE = "Asia/Seoul"
DEFAULT_KRX_REGULAR_OPEN = "09:00:00"
DEFAULT_KRX_REGULAR_CLOSE = "15:30:00"

PAUSE_REASON_CALENDAR_UNAVAILABLE = "KRX_CALENDAR_UNAVAILABLE"
PAUSE_REASON_CALENDAR_STALE = "KRX_CALENDAR_STALE"
PAUSE_REASON_MARKET_CLOSED = "KRX_MARKET_CLOSED"
