"""Post-exit re-entry cooldown shadow — RESEARCH ONLY (REAL entry 무영향)."""

from __future__ import annotations

FAMILY = "POST_EXIT_REENTRY_COOLDOWN_SHADOW_V1"
RULE_VERSION = "reentry_cooldown_shadow_v1"

VARIANT_R0 = "R0"
VARIANT_R1 = "R1"
VARIANT_R2 = "R2"
VARIANT_R3 = "R3"

R0_SECONDS = 0
R1_SECONDS = 60
R2_SECONDS = 180
R3_SECONDS = 300

VARIANT_SECONDS = {
    VARIANT_R0: R0_SECONDS,
    VARIANT_R1: R1_SECONDS,
    VARIANT_R2: R2_SECONDS,
    VARIANT_R3: R3_SECONDS,
}

STATUS_OBSERVED = "OBSERVED"
STATUS_COMPLETED = "COMPLETED"
