"""STEP N2 — News/Notice Collector 상수 (수집 전용, Symbol/AI 연동 금지)."""

from __future__ import annotations

SOURCE_TYPE_UPBIT_NOTICE = "UPBIT_NOTICE"
SOURCE_TYPE_CRYPTO_NEWS = "CRYPTO_NEWS"

SOURCE_CODE_UPBIT_NOTICE = "UPBIT_NOTICE"
SOURCE_CODE_CRYPTO_NEWS = "CRYPTO_NEWS"

# 종목 매핑 금지 — placeholder 만 사용 (news_article_symbol 링크 생성 안 함)
PLACEHOLDER_EXCHANGE_UPBIT = "UPBIT"
PLACEHOLDER_SYMBOL_NOTICE = "_NOTICE_"
PLACEHOLDER_SYMBOL_CRYPTO = "_CRYPTO_"

STATUS_ACTIVE = "ACTIVE"
STATUS_UPDATED = "UPDATED"

LANGUAGE_KO = "ko"

# rule 기반 category (AI 분류 금지)
CATEGORY_LISTING = "LISTING"
CATEGORY_DELISTING = "DELISTING"
CATEGORY_DEPOSIT_WITHDRAWAL = "DEPOSIT_WITHDRAWAL"
CATEGORY_MAINTENANCE = "MAINTENANCE"
CATEGORY_CAUTION = "CAUTION"
CATEGORY_TRADING_SUPPORT = "TRADING_SUPPORT"
CATEGORY_SYSTEM = "SYSTEM"
CATEGORY_GENERAL = "GENERAL"

NOTICE_PUBLIC_URL_TEMPLATE = (
    "https://www.upbit.com/service_center/notice?id={notice_id}"
)

CRYPTO_NEWS_PROVIDER_NAVER = "NAVER"
CRYPTO_NEWS_PROVIDER_NOT_AVAILABLE = "NEWS_PROVIDER_NOT_AVAILABLE"
