"""STEP N3.1 — Symbol Mapping Quality 상수."""

from __future__ import annotations

QUALITY_POLICY_VERSION = "symbol_mapping_quality_v2"

QUALITY_TRUSTED = "TRUSTED"
QUALITY_REVIEW_REQUIRED = "REVIEW_REQUIRED"
QUALITY_AMBIGUOUS = "AMBIGUOUS"
QUALITY_REJECTED = "REJECTED"

# N4 소비 계약: TRUSTED 만 기본 소비
N4_CONSUMABLE_QUALITY = frozenset({QUALITY_TRUSTED})

# 긍정 crypto context (AI 판단 금지 — keyword only)
CRYPTO_CONTEXT_KEYWORDS = (
    "토큰",
    "코인",
    "가상자산",
    "암호화폐",
    "블록체인",
    "상장",
    "거래지원",
    "거래 지원",
    "입출금",
    "에어드랍",
    "메인넷",
    "네트워크",
    "token",
    "coin",
    "crypto",
    "blockchain",
    "listing",
    "airdrop",
    "mainnet",
    "deposit",
    "withdrawal",
    "마켓",
    "market",
)

# 고빈도 일반 영어 어휘 ∩ universe alias 충돌 판별용 (코인 blacklist 아님)
# universe에서 추출한 latin alias와 교집합만 collision 후보가 됨
COMMON_ENGLISH_LEXICON = frozenset(
    {
        "A",
        "ABOUT",
        "ACE",
        "ACT",
        "ADD",
        "AFTER",
        "AGAIN",
        "AGE",
        "AGO",
        "AIR",
        "ALL",
        "ALSO",
        "AND",
        "ANY",
        "ARE",
        "ART",
        "ASK",
        "AT",
        "AUCTION",
        "BACK",
        "BAD",
        "BE",
        "BEEN",
        "BEFORE",
        "BEST",
        "BIG",
        "BOX",
        "BUT",
        "BUY",
        "BY",
        "CALL",
        "CAN",
        "CAR",
        "CASE",
        "CAT",
        "CITY",
        "COME",
        "COMPANY",
        "COULD",
        "DAY",
        "DID",
        "DO",
        "DOG",
        "DOWN",
        "EACH",
        "END",
        "EVEN",
        "EVER",
        "EVERY",
        "FACE",
        "FACT",
        "FAR",
        "FEE",
        "FEEL",
        "FEW",
        "FIND",
        "FIRST",
        "FLOW",
        "FOR",
        "FORM",
        "FROM",
        "FUN",
        "GAS",
        "GET",
        "GIVE",
        "GO",
        "GOOD",
        "GREAT",
        "GROUP",
        "HAD",
        "HAND",
        "HAS",
        "HAVE",
        "HE",
        "HELP",
        "HER",
        "HERE",
        "HIGH",
        "HIM",
        "HIS",
        "HOME",
        "HOT",
        "HOW",
        "I",
        "ID",
        "IF",
        "IN",
        "INTO",
        "IS",
        "IT",
        "ITS",
        "JUST",
        "KEEP",
        "KEY",
        "KNOW",
        "LARGE",
        "LAST",
        "LAYER",
        "LEAVE",
        "LEFT",
        "LIFE",
        "LIKE",
        "LINE",
        "LINK",
        "LIST",
        "LITTLE",
        "LONG",
        "LOOK",
        "MADE",
        "MAKE",
        "MAN",
        "MANY",
        "MASK",
        "MAY",
        "ME",
        "MEAN",
        "MEN",
        "MIGHT",
        "MORE",
        "MOST",
        "MOVE",
        "MUCH",
        "MUST",
        "MY",
        "NAME",
        "NEAR",
        "NEED",
        "NET",
        "NEVER",
        "NEW",
        "NEXT",
        "NO",
        "NOT",
        "NOW",
        "NUMBER",
        "OF",
        "OFF",
        "OLD",
        "ON",
        "ONE",
        "ONLY",
        "OPEN",
        "OR",
        "ORDER",
        "OTHER",
        "OUR",
        "OUT",
        "OVER",
        "OWN",
        "PART",
        "PEOPLE",
        "PER",
        "PLACE",
        "PLAY",
        "POINT",
        "PORT",
        "PUT",
        "RIGHT",
        "RUN",
        "SAID",
        "SAME",
        "SAND",
        "SAY",
        "SEE",
        "SET",
        "SHE",
        "SHOULD",
        "SHOW",
        "SIDE",
        "SMALL",
        "SO",
        "SOME",
        "STILL",
        "STORY",
        "SUCH",
        "TAKE",
        "TELL",
        "THAN",
        "THAT",
        "THE",
        "THEIR",
        "THEM",
        "THEN",
        "THERE",
        "THESE",
        "THEY",
        "THING",
        "THINK",
        "THIS",
        "THOSE",
        "THROUGH",
        "TIME",
        "TO",
        "TOO",
        "TOP",
        "TURN",
        "TWO",
        "UNDER",
        "UP",
        "US",
        "USE",
        "VERY",
        "VIA",
        "WANT",
        "WAS",
        "WATER",
        "WAY",
        "WE",
        "WELL",
        "WERE",
        "WHAT",
        "WHEN",
        "WHERE",
        "WHICH",
        "WHILE",
        "WHO",
        "WHY",
        "WILL",
        "WITH",
        "WORD",
        "WORK",
        "WORLD",
        "WOULD",
        "YEAR",
        "YES",
        "YOU",
        "YOUR",
    }
)

# alias별 부정 context (일반 의미) — 중앙 policy
NEGATIVE_CONTEXT_PATTERNS: dict[str, tuple[str, ...]] = {
    "AUCTION": (
        r"nft\s+auction",
        r"auction\s+platform",
        r"auction\s+house",
        r"fixed[-_]?price[-_]?auction",
        r"/auction/",
        r"경매",
        r"옥션\s*플랫폼",
    ),
    "GAS": (
        r"gas\s*fee",
        r"transaction\s+gas",
        r"network\s+gas",
        r"가스비",
        r"가스\s*수수료",
        r"트랜잭션\s*가스",
    ),
    "MASK": (r"face\s*mask", r"마스크\s*착용", r"보호\s*마스크"),
    "FLOW": (r"cash\s*flow", r"work\s*flow", r"workflow", r"흐름"),
    "NEAR": (r"near\s+term", r"near\s+future", r"가까운"),
    "MOVE": (r"make\s+a\s+move", r"move\s+on", r"이동"),
    "SAND": (r"sand\s+box", r"모래"),
    "STORY": (r"news\s+story", r"success\s+story", r"이야기", r"스토리"),
    "ONE": (r"\bone\s+of\b", r"\bthe\s+one\b"),
    "ID": (r"\bid\s*card\b", r"\buser\s*id\b", r"식별", r"아이디"),
    "ME": (r"\bcontact\s+me\b", r"\bfor\s+me\b"),
}

# token/coin 명시 context — collision alias를 TRUSTED로 올릴 때
TOKEN_EXPLICIT_PATTERNS: dict[str, tuple[str, ...]] = {
    "AUCTION": (
        r"auction\s+token",
        r"\$auction\b",
        r"\bauction\s+coin",
        r"에이션",
        r"옥션\s*토큰",
    ),
    "GAS": (
        r"\bgas\s+token\b",
        r"\bgas\s+airdrop\b",
        r"가스\s*에어드랍",
        r"가스\s*토큰",
        r"neo\s+gas",
    ),
}
