"""create strategy deployment pipeline table

Revision ID: 032733cd8b08
Revises: debbfa486383
Create Date: 2026-07-16 06:48:34.440570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '032733cd8b08'
down_revision: Union[str, Sequence[str], None] = 'debbfa486383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_deployment_pipeline',
    sa.Column('strategy_deployment_pipeline_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('strategy_selection_run_id', sa.BigInteger(), nullable=False),
    sa.Column('strategy_approval_run_id', sa.BigInteger(), nullable=True),
    sa.Column('strategy_deployment_id', sa.BigInteger(), nullable=True),
    sa.Column('strategy_runtime_switch_id', sa.BigInteger(), nullable=True),
    sa.Column('strategy_code', sa.String(length=100), nullable=True),
    sa.Column('market_code', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('status_code', sa.String(length=30), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('strategy_deployment_pipeline_id', name=op.f('pk_strategy_deployment_pipeline')),
    schema='trading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_deployment_pipeline', schema='trading')
    # ### end Alembic commands ###
