"""create ai candidate analysis tables

Revision ID: 08b8c97a2a64
Revises: 816fce436ae1
Create Date: 2026-07-14 20:53:37.124504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08b8c97a2a64'
down_revision: Union[str, Sequence[str], None] = '816fce436ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_analysis_run',
    sa.Column('analysis_run_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('source_candidate_run_id', sa.BigInteger(), nullable=False),
    sa.Column('exchange_code', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('requested_limit', sa.Integer(), nullable=False),
    sa.Column('selected_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status_code', sa.String(length=20), server_default=sa.text("'COMPLETED'"), nullable=False),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_candidate_run_id'], ['strategy.candidate_run.run_id'], name='fk_candidate_analysis_run_source_candidate_run', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_run_id', name=op.f('pk_candidate_analysis_run')),
    sa.UniqueConstraint('source_candidate_run_id', 'model_name', name='uq_candidate_analysis_run_source_model'),
    schema='ai'
    )
    op.create_table('candidate_analysis_result',
    sa.Column('analysis_result_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('analysis_run_id', sa.BigInteger(), nullable=False),
    sa.Column('rank_no', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('ai_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('action_code', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('context_used', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['ai.candidate_analysis_run.analysis_run_id'], name='fk_candidate_analysis_result_analysis_run', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_result_id', name=op.f('pk_candidate_analysis_result')),
    sa.UniqueConstraint('analysis_run_id', 'rank_no', name='uq_candidate_analysis_result_run_rank'),
    sa.UniqueConstraint('analysis_run_id', 'symbol', name='uq_candidate_analysis_result_run_symbol'),
    schema='ai'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_analysis_result', schema='ai')
    op.drop_table('candidate_analysis_run', schema='ai')
    # ### end Alembic commands ###
