"""create strategy selection run table

Revision ID: 0fe62ca07d50
Revises: 7ca511c09f1c
Create Date: 2026-07-16 05:35:55.155773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fe62ca07d50'
down_revision: Union[str, Sequence[str], None] = '7ca511c09f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_selection_run',
    sa.Column('strategy_selection_run_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('market_code', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('run_type', sa.String(length=30), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('status_code', sa.String(length=30), nullable=False),
    sa.Column('selected_strategy_code', sa.String(length=100), nullable=False),
    sa.Column('selected_performance_run_id', sa.BigInteger(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('risk_notes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('candidate_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('strategy_selection_run_id', name=op.f('pk_strategy_selection_run')),
    schema='ai'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_selection_run', schema='ai')
    # ### end Alembic commands ###
