"""create paper order table

Revision ID: 13f7e38de978
Revises: eb6db7134bae
Create Date: 2026-07-14 22:36:00.615398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f7e38de978'
down_revision: Union[str, Sequence[str], None] = 'eb6db7134bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_order',
    sa.Column('order_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('position_plan_id', sa.BigInteger(), nullable=True),
    sa.Column('exchange_code', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('status_code', sa.String(length=30), server_default=sa.text("'CREATED'"), nullable=False),
    sa.Column('requested_quantity', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('requested_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('filled_quantity', sa.Numeric(precision=28, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('average_fill_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk_paper_order')),
    schema='trading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_order', schema='trading')
    # ### end Alembic commands ###
