"""create persistent kill switch tables

Revision ID: 141b5230f0ef
Revises: f0591f0baeb2
Create Date: 2026-07-15 22:58:06.312908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141b5230f0ef'
down_revision: Union[str, Sequence[str], None] = 'f0591f0baeb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kill_switch',
    sa.Column('kill_switch_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('scope_code', sa.String(length=30), server_default=sa.text("'GLOBAL'"), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('activated_by', sa.String(length=100), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_by', sa.String(length=100), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('kill_switch_id', name=op.f('pk_kill_switch')),
    sa.UniqueConstraint('scope_code', name=op.f('uq_kill_switch_scope_code')),
    schema='operation'
    )
    op.create_table('kill_switch_history',
    sa.Column('kill_switch_history_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('scope_code', sa.String(length=30), nullable=False),
    sa.Column('action_code', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('kill_switch_history_id', name=op.f('pk_kill_switch_history')),
    schema='operation'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kill_switch_history', schema='operation')
    op.drop_table('kill_switch', schema='operation')
    # ### end Alembic commands ###
