"""create risk policy and position plan tables

Revision ID: 234f43fd1557
Revises: 9193f9b0bc0e

NOTE: 파일명은 news이나 실제로는 strategy.risk_policy / strategy.position_plan 생성.
Create Date: 2026-07-14 22:15:06.319779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234f43fd1557'
down_revision: Union[str, Sequence[str], None] = '9193f9b0bc0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_plan',
    sa.Column('position_plan_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('policy_id', sa.BigInteger(), nullable=True),
    sa.Column('exchange_code', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('order_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('stop_loss_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('take_profit_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('trailing_stop_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('maximum_loss_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('position_plan_id', name=op.f('pk_position_plan')),
    schema='strategy'
    )
    op.create_table('risk_policy',
    sa.Column('policy_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('policy_name', sa.String(length=100), nullable=False),
    sa.Column('position_sizing_mode', sa.String(length=30), nullable=False),
    sa.Column('fixed_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('portfolio_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('risk_per_trade_ratio', sa.Numeric(precision=10, scale=6), server_default=sa.text('0.01'), nullable=False),
    sa.Column('stop_loss_ratio', sa.Numeric(precision=10, scale=6), server_default=sa.text('0.03'), nullable=False),
    sa.Column('take_profit_ratio', sa.Numeric(precision=10, scale=6), server_default=sa.text('0.06'), nullable=False),
    sa.Column('trailing_stop_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('maximum_position_ratio', sa.Numeric(precision=10, scale=6), server_default=sa.text('0.20'), nullable=False),
    sa.Column('maximum_positions', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('minimum_order_amount', sa.Numeric(precision=20, scale=2), server_default=sa.text('10000'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('policy_id', name=op.f('pk_risk_policy')),
    sa.UniqueConstraint('policy_name', name='uq_risk_policy_policy_name'),
    schema='strategy'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_policy', schema='strategy')
    op.drop_table('position_plan', schema='strategy')
    # ### end Alembic commands ###
