"""create broker account snapshot tables

Revision ID: 29e7a91957c4
Revises: f2cbe1d80112
Create Date: 2026-07-15 20:49:05.754534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29e7a91957c4'
down_revision: Union[str, Sequence[str], None] = 'f2cbe1d80112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_account_snapshot',
    sa.Column('broker_account_snapshot_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('broker_code', sa.String(length=30), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('currency_code', sa.String(length=10), server_default=sa.text("'KRW'"), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('available_order_amount', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_purchase_amount', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_evaluation_amount', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_profit_loss', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_return_rate', sa.Numeric(precision=12, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('synchronized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('broker_account_snapshot_id', name=op.f('pk_broker_account_snapshot')),
    sa.UniqueConstraint('broker_code', 'account_number', name='uq_broker_account_snapshot_account'),
    schema='trading'
    )
    op.create_table('broker_position_snapshot',
    sa.Column('broker_position_snapshot_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('broker_code', sa.String(length=30), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('exchange_code', sa.String(length=20), server_default=sa.text("'KRX'"), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('available_quantity', sa.Numeric(precision=28, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('average_purchase_price', sa.Numeric(precision=20, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('purchase_amount', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('evaluation_amount', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('profit_loss', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('return_rate', sa.Numeric(precision=12, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('synchronized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('broker_position_snapshot_id', name=op.f('pk_broker_position_snapshot')),
    sa.UniqueConstraint('broker_code', 'account_number', 'exchange_code', 'symbol', name='uq_broker_position_snapshot_symbol'),
    schema='trading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broker_position_snapshot', schema='trading')
    op.drop_table('broker_account_snapshot', schema='trading')
    # ### end Alembic commands ###
