"""create market price daily table

Revision ID: 2ee327dfb420
Revises: 3d46460efdbb
Create Date: 2026-07-13 22:42:46.667539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee327dfb420'
down_revision: Union[str, Sequence[str], None] = '3d46460efdbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_daily',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='Trading date'),
    sa.Column('open_price', sa.Numeric(precision=20, scale=8), nullable=False, comment='Open price'),
    sa.Column('high_price', sa.Numeric(precision=20, scale=8), nullable=False, comment='High price'),
    sa.Column('low_price', sa.Numeric(precision=20, scale=8), nullable=False, comment='Low price'),
    sa.Column('close_price', sa.Numeric(precision=20, scale=8), nullable=False, comment='Close price'),
    sa.Column('volume', sa.Numeric(precision=28, scale=8), server_default=sa.text('0'), nullable=False, comment='Trading volume'),
    sa.Column('trade_value', sa.Numeric(precision=28, scale=8), server_default=sa.text('0'), nullable=False, comment='Trading value'),
    sa.Column('change_rate', sa.Numeric(precision=12, scale=6), nullable=True, comment='Change rate in percent'),
    sa.Column('source', sa.String(length=30), nullable=False, comment='Data source (KIWOOM, UPBIT, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('close_price >= 0', name=op.f('ck_price_daily_close_price_nonnegative')),
    sa.CheckConstraint('high_price >= 0', name=op.f('ck_price_daily_high_price_nonnegative')),
    sa.CheckConstraint('high_price >= low_price', name=op.f('ck_price_daily_high_not_below_low')),
    sa.CheckConstraint('low_price >= 0', name=op.f('ck_price_daily_low_price_nonnegative')),
    sa.CheckConstraint('open_price >= 0', name=op.f('ck_price_daily_open_price_nonnegative')),
    sa.CheckConstraint('trade_value >= 0', name=op.f('ck_price_daily_trade_value_nonnegative')),
    sa.CheckConstraint('volume >= 0', name=op.f('ck_price_daily_volume_nonnegative')),
    sa.ForeignKeyConstraint(['instrument_id'], ['market.instrument.instrument_id'], name='fk_price_daily_instrument_id_instrument', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', 'trade_date', name=op.f('pk_price_daily')),
    schema='market'
    )
    op.create_index('ix_price_daily_trade_date', 'price_daily', ['trade_date'], unique=False, schema='market')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_daily_trade_date', table_name='price_daily', schema='market')
    op.drop_table('price_daily', schema='market')
    # ### end Alembic commands ###
