"""create pipeline run tables

Revision ID: 36b7c7e6307d
Revises: 86706db6ba99
Create Date: 2026-07-14 23:36:12.336679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36b7c7e6307d'
down_revision: Union[str, Sequence[str], None] = '86706db6ba99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_run',
    sa.Column('pipeline_run_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('pipeline_name', sa.String(length=100), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), server_default=sa.text("'MANUAL'"), nullable=False),
    sa.Column('status_code', sa.String(length=30), server_default=sa.text("'RUNNING'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('pipeline_run_id', name=op.f('pk_pipeline_run')),
    schema='operation'
    )
    op.create_table('pipeline_step_run',
    sa.Column('pipeline_step_run_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('pipeline_run_id', sa.BigInteger(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('status_code', sa.String(length=30), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['operation.pipeline_run.pipeline_run_id'], name='fk_pipeline_step_run_pipeline', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_step_run_id', name=op.f('pk_pipeline_step_run')),
    sa.UniqueConstraint('pipeline_run_id', 'step_name', name='uq_pipeline_step_run_pipeline_step'),
    schema='operation'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_step_run', schema='operation')
    op.drop_table('pipeline_run', schema='operation')
    # ### end Alembic commands ###
