"""create position limit table

Revision ID: 3ab3e6efd4a9
Revises: 921a2785a432
Create Date: 2026-07-15 23:28:39.238806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab3e6efd4a9'
down_revision: Union[str, Sequence[str], None] = '921a2785a432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_limit',
    sa.Column('position_limit_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('broker_code', sa.String(length=30), server_default=sa.text("'KIWOOM'"), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('exchange_code', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('max_quantity', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('max_position_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('max_position_weight', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('position_limit_id', name=op.f('pk_position_limit')),
    sa.UniqueConstraint('broker_code', 'account_number', 'exchange_code', 'symbol', name='uq_position_limit_scope'),
    schema='operation'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position_limit', schema='operation')
    # ### end Alembic commands ###
