"""create walk forward window metric table

Revision ID: 3c78feee01b1
Revises: d58bfcc54d62
Create Date: 2026-07-16 00:18:13.564857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c78feee01b1'
down_revision: Union[str, Sequence[str], None] = 'd58bfcc54d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walk_forward_window_metric',
    sa.Column('walk_forward_window_metric_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('strategy_performance_run_id', sa.BigInteger(), nullable=False),
    sa.Column('window_no', sa.Integer(), nullable=False),
    sa.Column('train_start_date', sa.Date(), nullable=False),
    sa.Column('train_end_date', sa.Date(), nullable=False),
    sa.Column('test_start_date', sa.Date(), nullable=False),
    sa.Column('test_end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('final_capital', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_return_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('maximum_drawdown_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('sharpe_ratio', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('total_trade_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('net_profit_amount', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('parameter_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('walk_forward_window_metric_id', name=op.f('pk_walk_forward_window_metric')),
    sa.UniqueConstraint('strategy_performance_run_id', 'window_no', name='uq_walk_forward_window_metric'),
    schema='trading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walk_forward_window_metric', schema='trading')
    # ### end Alembic commands ###
