"""create dart disclosure table

Revision ID: 530f1321c2d5
Revises: 08b8c97a2a64
Create Date: 2026-07-14 21:02:29.126742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '530f1321c2d5'
down_revision: Union[str, Sequence[str], None] = '08b8c97a2a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dart_disclosure',
    sa.Column('disclosure_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('receipt_no', sa.String(length=20), nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('corp_name', sa.String(length=200), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=True),
    sa.Column('report_name', sa.String(length=500), nullable=False),
    sa.Column('filer_name', sa.String(length=200), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('disclosure_id', name=op.f('pk_dart_disclosure')),
    sa.UniqueConstraint('receipt_no', name='uq_dart_disclosure_receipt_no'),
    schema='disclosure'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dart_disclosure', schema='disclosure')
    # ### end Alembic commands ###
