"""create market instrument table

Revision ID: 63974784f82a
Revises: a93930601b5e
Create Date: 2026-07-13 20:28:12.573162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63974784f82a'
down_revision: Union[str, Sequence[str], None] = 'a93930601b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument',
    sa.Column('instrument_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False, comment='Asset type (STOCK, CRYPTO, ETF, INDEX)'),
    sa.Column('exchange_code', sa.String(length=20), nullable=False, comment='Exchange code (KRX, UPBIT, etc.)'),
    sa.Column('symbol', sa.String(length=30), nullable=False, comment='Trading symbol'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Instrument name'),
    sa.Column('currency_code', sa.String(length=10), server_default=sa.text("'KRW'"), nullable=False, comment='Trading currency'),
    sa.Column('listed_date', sa.Date(), nullable=True, comment='Listing date'),
    sa.Column('delisted_date', sa.Date(), nullable=True, comment='Delisting date'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Whether the instrument is active'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Additional metadata from external APIs'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("asset_type IN ('STOCK', 'CRYPTO', 'ETF', 'INDEX')", name=op.f('ck_instrument_ck_instrument_asset_type')),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_instrument')),
    sa.UniqueConstraint('exchange_code', 'symbol', name='uq_instrument_exchange_symbol'),
    schema='market'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instrument', schema='market')
    # ### end Alembic commands ###
