"""create trading order tables

Revision ID: 7a73b030ced6
Revises: 83f71246bf75
Create Date: 2026-07-17 08:15:03.044591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a73b030ced6'
down_revision: Union[str, Sequence[str], None] = '83f71246bf75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_order',
    sa.Column('order_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('client_order_id', sa.String(length=50), nullable=False),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('broker_code', sa.String(length=30), nullable=False),
    sa.Column('exchange_code', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('strategy_code', sa.String(length=100), nullable=True),
    sa.Column('strategy_deployment_id', sa.BigInteger(), nullable=True),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=True),
    sa.Column('position_id', sa.BigInteger(), nullable=True),
    sa.Column('side_code', sa.String(length=10), nullable=False),
    sa.Column('order_type_code', sa.String(length=20), nullable=False),
    sa.Column('time_in_force_code', sa.String(length=10), server_default=sa.text("'DAY'"), nullable=False),
    sa.Column('order_quantity', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('order_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('filled_quantity', sa.Numeric(precision=28, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=28, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('filled_amount', sa.Numeric(precision=24, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('average_fill_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('status_code', sa.String(length=30), server_default=sa.text("'CREATED'"), nullable=False),
    sa.Column('reject_code', sa.String(length=100), nullable=True),
    sa.Column('reject_message', sa.Text(), nullable=True),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('original_order_id', sa.BigInteger(), nullable=True),
    sa.Column('replaced_order_id', sa.BigInteger(), nullable=True),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('version_no', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk_trading_order')),
    sa.UniqueConstraint('client_order_id', name='uq_trading_order_client_order_id'),
    schema='trading'
    )
    op.create_index('ix_trading_order_account_status', 'trading_order', ['account_id', 'status_code'], unique=False, schema='trading')
    op.create_index('ix_trading_order_symbol_created', 'trading_order', ['exchange_code', 'symbol', 'created_at'], unique=False, schema='trading')
    op.create_table('trading_order_status_history',
    sa.Column('order_status_history_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('previous_status_code', sa.String(length=30), nullable=True),
    sa.Column('current_status_code', sa.String(length=30), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=100), server_default=sa.text("'SYSTEM'"), nullable=False),
    sa.Column('detail_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('order_status_history_id', name=op.f('pk_trading_order_status_history')),
    schema='trading'
    )
    op.create_index('ix_order_status_history_order', 'trading_order_status_history', ['order_id', 'created_at'], unique=False, schema='trading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_status_history_order', table_name='trading_order_status_history', schema='trading')
    op.drop_table('trading_order_status_history', schema='trading')
    op.drop_index('ix_trading_order_symbol_created', table_name='trading_order', schema='trading')
    op.drop_index('ix_trading_order_account_status', table_name='trading_order', schema='trading')
    op.drop_table('trading_order', schema='trading')
    # ### end Alembic commands ###
