"""create strategy leaderboard tables

Revision ID: 7ca511c09f1c
Revises: 3c78feee01b1
Create Date: 2026-07-16 00:24:26.643057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ca511c09f1c'
down_revision: Union[str, Sequence[str], None] = '3c78feee01b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_leaderboard_entry',
    sa.Column('strategy_leaderboard_entry_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('strategy_leaderboard_snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('rank_no', sa.Integer(), nullable=False),
    sa.Column('strategy_performance_run_id', sa.BigInteger(), nullable=False),
    sa.Column('strategy_code', sa.String(length=100), nullable=False),
    sa.Column('market_code', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('run_type', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_return_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('maximum_drawdown_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('sharpe_ratio', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('total_trade_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('strategy_leaderboard_entry_id', name=op.f('pk_strategy_leaderboard_entry')),
    sa.UniqueConstraint('strategy_leaderboard_snapshot_id', 'rank_no', name='uq_strategy_leaderboard_entry_rank'),
    sa.UniqueConstraint('strategy_leaderboard_snapshot_id', 'strategy_performance_run_id', name='uq_strategy_leaderboard_entry_run'),
    schema='trading'
    )
    op.create_table('strategy_leaderboard_snapshot',
    sa.Column('strategy_leaderboard_snapshot_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('run_type', sa.String(length=30), nullable=True),
    sa.Column('market_code', sa.String(length=30), nullable=True),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('minimum_trade_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('strategy_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('ranking_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('strategy_leaderboard_snapshot_id', name=op.f('pk_strategy_leaderboard_snapshot')),
    sa.UniqueConstraint('snapshot_date', 'run_type', 'market_code', 'symbol', 'minimum_trade_count', name='uq_strategy_leaderboard_snapshot_scope'),
    schema='trading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_leaderboard_snapshot', schema='trading')
    op.drop_table('strategy_leaderboard_entry', schema='trading')
    # ### end Alembic commands ###
