"""create candidate screening tables

Revision ID: 816fce436ae1
Revises: 2ee327dfb420
Create Date: 2026-07-14 20:29:46.777526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '816fce436ae1'
down_revision: Union[str, Sequence[str], None] = '2ee327dfb420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_run',
    sa.Column('run_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('exchange_code', sa.String(length=20), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('run_type', sa.String(length=20), server_default=sa.text("'DAILY'"), nullable=False),
    sa.Column('requested_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('evaluated_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('skipped_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('selected_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('minimum_score', sa.Numeric(precision=6, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('require_all_rules', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status_code', sa.String(length=20), server_default=sa.text("'COMPLETED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_candidate_run')),
    sa.UniqueConstraint('exchange_code', 'as_of_date', 'run_type', name='uq_candidate_run_exchange_date_type'),
    schema='strategy'
    )
    op.create_table('candidate_result',
    sa.Column('result_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('rank_no', sa.Integer(), nullable=False),
    sa.Column('exchange_code', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('rules_passed_count', sa.Integer(), nullable=False),
    sa.Column('all_rules_passed', sa.Boolean(), nullable=False),
    sa.Column('rule_result', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['strategy.candidate_run.run_id'], name='fk_candidate_result_run_id_candidate_run', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id', name=op.f('pk_candidate_result')),
    sa.UniqueConstraint('run_id', 'rank_no', name='uq_candidate_result_run_rank'),
    sa.UniqueConstraint('run_id', 'symbol', name='uq_candidate_result_run_symbol'),
    schema='strategy'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_result', schema='strategy')
    op.drop_table('candidate_run', schema='strategy')
    # ### end Alembic commands ###
