"""create strategy deployment performance table

Revision ID: 83f71246bf75
Revises: 032733cd8b08
Create Date: 2026-07-16 07:02:08.121059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83f71246bf75'
down_revision: Union[str, Sequence[str], None] = '032733cd8b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_deployment_performance',
    sa.Column('strategy_deployment_performance_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('strategy_deployment_id', sa.BigInteger(), nullable=False),
    sa.Column('strategy_code', sa.String(length=100), nullable=False),
    sa.Column('status_code', sa.String(length=30), nullable=False),
    sa.Column('total_trade_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_return_rate', sa.Numeric(precision=18, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('maximum_drawdown_rate', sa.Numeric(precision=18, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=18, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('consecutive_losses', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('check_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('strategy_deployment_performance_id', name=op.f('pk_strategy_deployment_performance')),
    schema='trading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_deployment_performance', schema='trading')
    # ### end Alembic commands ###
