"""create job run history table

Revision ID: 86706db6ba99
Revises: 8fe17ae5b326

NOTE: no-op revision. 실제 job_run_history 생성은 8fe17ae5b326에서 수행됨.
Create Date: 2026-07-14 23:18:25.449412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86706db6ba99'
down_revision: Union[str, Sequence[str], None] = '8fe17ae5b326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
