"""create job run history table

Revision ID: 8fe17ae5b326
Revises: eabcaef185e2
Create Date: 2026-07-14 23:17:08.941759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fe17ae5b326'
down_revision: Union[str, Sequence[str], None] = 'eabcaef185e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_run_history',
    sa.Column('job_run_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('job_group', sa.String(length=50), server_default=sa.text("'DEFAULT'"), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), server_default=sa.text("'MANUAL'"), nullable=False),
    sa.Column('status_code', sa.String(length=30), server_default=sa.text("'RUNNING'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('job_run_id', name=op.f('pk_job_run_history')),
    schema='operation'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_run_history', schema='operation')
    # ### end Alembic commands ###
