"""create news article and summary tables

Revision ID: 9193f9b0bc0e
Revises: 530f1321c2d5
Create Date: 2026-07-14 21:21:43.145146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9193f9b0bc0e'
down_revision: Union[str, Sequence[str], None] = '530f1321c2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_article',
    sa.Column('article_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('exchange_code', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('query_text', sa.String(length=300), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_link', sa.Text(), nullable=True),
    sa.Column('naver_link', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_code', sa.String(length=30), server_default=sa.text("'NAVER'"), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('article_id', name=op.f('pk_news_article')),
    sa.UniqueConstraint('content_hash', name='uq_news_article_content_hash'),
    schema='news'
    )
    op.create_table('news_summary',
    sa.Column('summary_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('importance_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news.news_article.article_id'], name='fk_news_summary_article', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('summary_id', name=op.f('pk_news_summary')),
    sa.UniqueConstraint('article_id', 'model_name', name='uq_news_summary_article_model'),
    schema='news'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_summary', schema='news')
    op.drop_table('news_article', schema='news')
    # ### end Alembic commands ###
