"""create risk event table

Revision ID: 921a2785a432
Revises: 141b5230f0ef
Create Date: 2026-07-15 23:15:07.393381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '921a2785a432'
down_revision: Union[str, Sequence[str], None] = '141b5230f0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_event',
    sa.Column('risk_event_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_level', sa.String(length=20), nullable=False),
    sa.Column('broker_code', sa.String(length=30), server_default=sa.text("'KIWOOM'"), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('current_loss_amount', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('loss_limit_amount', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('risk_event_id', name=op.f('pk_risk_event')),
    schema='operation'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_event', schema='operation')
    # ### end Alembic commands ###
