"""create broker pending order table

Revision ID: 96c0ebbf4748
Revises: 29e7a91957c4
Create Date: 2026-07-15 21:22:02.274826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96c0ebbf4748'
down_revision: Union[str, Sequence[str], None] = '29e7a91957c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_pending_order',
    sa.Column('broker_pending_order_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('broker_code', sa.String(length=30), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('broker_order_id', sa.String(length=50), nullable=False),
    sa.Column('exchange_code', sa.String(length=20), server_default=sa.text("'KRX'"), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('order_quantity', sa.Numeric(precision=28, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('order_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('filled_quantity', sa.Numeric(precision=28, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=28, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('average_fill_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('status_code', sa.String(length=30), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('synchronized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('broker_pending_order_id', name=op.f('pk_broker_pending_order')),
    sa.UniqueConstraint('broker_code', 'account_number', 'broker_order_id', name='uq_broker_pending_order_number'),
    schema='trading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broker_pending_order', schema='trading')
    # ### end Alembic commands ###
