"""create strategy runtime switch table

Revision ID: b19e8da6c240
Revises: baddac6ef7dc
Create Date: 2026-07-16 06:16:54.802775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b19e8da6c240'
down_revision: Union[str, Sequence[str], None] = 'baddac6ef7dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_runtime_switch',
    sa.Column('strategy_runtime_switch_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('previous_deployment_id', sa.BigInteger(), nullable=True),
    sa.Column('target_deployment_id', sa.BigInteger(), nullable=False),
    sa.Column('status_code', sa.String(length=30), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('dry_run_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('previous_state_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('target_state_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('strategy_runtime_switch_id', name=op.f('pk_strategy_runtime_switch')),
    schema='trading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_runtime_switch', schema='trading')
    # ### end Alembic commands ###
