"""create daily operations report table

Revision ID: b3668618cbca
Revises: da0a8be262d7
Create Date: 2026-07-14 23:56:52.045073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3668618cbca'
down_revision: Union[str, Sequence[str], None] = 'da0a8be262d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_operations_report',
    sa.Column('report_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('exchange_code', sa.String(length=20), nullable=False),
    sa.Column('pipeline_status_code', sa.String(length=30), nullable=True),
    sa.Column('job_success_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('job_failed_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('selected_candidate_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('ai_candidate_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('approved_position_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_order_amount', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('realized_profit_loss', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('unrealized_profit_loss', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('incident_summary', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('report_id', name=op.f('pk_daily_operations_report')),
    sa.UniqueConstraint('report_date', 'exchange_code', name='uq_daily_operations_report_date_exchange'),
    schema='operation'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_operations_report', schema='operation')
    # ### end Alembic commands ###
