"""create strategy deployment tables

Revision ID: baddac6ef7dc
Revises: 0fe62ca07d50
Create Date: 2026-07-16 05:58:04.621490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baddac6ef7dc'
down_revision: Union[str, Sequence[str], None] = '0fe62ca07d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_deployment',
    sa.Column('strategy_deployment_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('strategy_code', sa.String(length=100), nullable=False),
    sa.Column('strategy_performance_run_id', sa.BigInteger(), nullable=False),
    sa.Column('market_code', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('mode_code', sa.String(length=20), server_default=sa.text("'PAPER'"), nullable=False),
    sa.Column('status_code', sa.String(length=30), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('parameter_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_deployment_id', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('strategy_deployment_id', name=op.f('pk_strategy_deployment')),
    sa.UniqueConstraint('market_code', 'symbol', 'mode_code', 'status_code', name='uq_strategy_deployment_active_scope'),
    schema='trading'
    )
    op.create_table('strategy_deployment_history',
    sa.Column('strategy_deployment_history_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('strategy_deployment_id', sa.BigInteger(), nullable=False),
    sa.Column('action_code', sa.String(length=30), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('strategy_deployment_history_id', name=op.f('pk_strategy_deployment_history')),
    schema='trading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_deployment_history', schema='trading')
    op.drop_table('strategy_deployment', schema='trading')
    # ### end Alembic commands ###
