"""create broker recovery tables

Revision ID: d4482c3ad2a2
Revises: 96c0ebbf4748
Create Date: 2026-07-15 22:10:13.220494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4482c3ad2a2'
down_revision: Union[str, Sequence[str], None] = '96c0ebbf4748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_recovery_run',
    sa.Column('broker_recovery_run_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('status_code', sa.String(length=30), server_default=sa.text("'RUNNING'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('broker_recovery_run_id', name=op.f('pk_broker_recovery_run')),
    schema='operation'
    )
    op.create_table('broker_recovery_step',
    sa.Column('broker_recovery_step_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('broker_recovery_run_id', sa.BigInteger(), nullable=False),
    sa.Column('component_code', sa.String(length=50), nullable=False),
    sa.Column('status_code', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('broker_recovery_step_id', name=op.f('pk_broker_recovery_step')),
    schema='operation'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broker_recovery_step', schema='operation')
    op.drop_table('broker_recovery_run', schema='operation')
    # ### end Alembic commands ###
