"""create strategy performance tables

Revision ID: d58bfcc54d62
Revises: 3ab3e6efd4a9
Create Date: 2026-07-16 00:00:08.632150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd58bfcc54d62'
down_revision: Union[str, Sequence[str], None] = '3ab3e6efd4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_performance_metric',
    sa.Column('strategy_performance_metric_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('strategy_performance_run_id', sa.BigInteger(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('final_capital', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_return_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('annualized_return_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('maximum_drawdown_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volatility_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('total_trade_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('winning_trade_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('losing_trade_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('average_profit_amount', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('average_loss_amount', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('gross_profit_amount', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('gross_loss_amount', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('net_profit_amount', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('strategy_performance_metric_id', name=op.f('pk_strategy_performance_metric')),
    sa.UniqueConstraint('strategy_performance_run_id', name='uq_strategy_performance_metric_run'),
    schema='trading'
    )
    op.create_table('strategy_performance_run',
    sa.Column('strategy_performance_run_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('strategy_code', sa.String(length=100), nullable=False),
    sa.Column('run_type', sa.String(length=30), nullable=False),
    sa.Column('status_code', sa.String(length=30), server_default=sa.text("'RUNNING'"), nullable=False),
    sa.Column('market_code', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('period_start_date', sa.Date(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('parameter_hash', sa.String(length=64), nullable=False),
    sa.Column('parameter_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('strategy_performance_run_id', name=op.f('pk_strategy_performance_run')),
    sa.UniqueConstraint('strategy_code', 'run_type', 'market_code', 'symbol', 'period_start_date', 'period_end_date', 'parameter_hash', name='uq_strategy_performance_run'),
    schema='trading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_performance_run', schema='trading')
    op.drop_table('strategy_performance_metric', schema='trading')
    # ### end Alembic commands ###
