"""create trading calendar table

Revision ID: da0a8be262d7
Revises: 36b7c7e6307d
Create Date: 2026-07-14 23:47:48.678064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0a8be262d7'
down_revision: Union[str, Sequence[str], None] = '36b7c7e6307d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_calendar_day',
    sa.Column('calendar_day_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('exchange_code', sa.String(length=20), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('is_trading_day', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('holiday_name', sa.String(length=200), nullable=True),
    sa.Column('source_code', sa.String(length=30), server_default=sa.text("'MANUAL'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('calendar_day_id', name=op.f('pk_trading_calendar_day')),
    sa.UniqueConstraint('exchange_code', 'calendar_date', name='uq_trading_calendar_exchange_date'),
    schema='operation'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trading_calendar_day', schema='operation')
    # ### end Alembic commands ###
