"""create strategy approval run table

Revision ID: debbfa486383
Revises: b19e8da6c240
Create Date: 2026-07-16 06:33:29.489954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'debbfa486383'
down_revision: Union[str, Sequence[str], None] = 'b19e8da6c240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_approval_run',
    sa.Column('strategy_approval_run_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('strategy_selection_run_id', sa.BigInteger(), nullable=False),
    sa.Column('strategy_performance_run_id', sa.BigInteger(), nullable=False),
    sa.Column('strategy_code', sa.String(length=100), nullable=False),
    sa.Column('market_code', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('decision_code', sa.String(length=30), nullable=False),
    sa.Column('status_code', sa.String(length=30), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('automatic_approval', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('decided_by', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('policy_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('check_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('deployment_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('strategy_approval_run_id', name=op.f('pk_strategy_approval_run')),
    schema='trading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_approval_run', schema='trading')
    # ### end Alembic commands ###
