"""create paper account position and trade tables

Revision ID: eabcaef185e2
Revises: 13f7e38de978
Create Date: 2026-07-14 22:49:27.564624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eabcaef185e2'
down_revision: Union[str, Sequence[str], None] = '13f7e38de978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_account',
    sa.Column('account_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('currency_code', sa.String(length=10), server_default=sa.text("'KRW'"), nullable=False),
    sa.Column('initial_cash', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('available_cash', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('realized_profit_loss', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('account_id', name=op.f('pk_paper_account')),
    sa.UniqueConstraint('account_name', name='uq_paper_account_account_name'),
    schema='trading'
    )
    op.create_table('paper_position',
    sa.Column('position_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('exchange_code', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('average_entry_price', sa.Numeric(precision=20, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('highest_price', sa.Numeric(precision=20, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('realized_profit_loss', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading.paper_account.account_id'], name='fk_paper_position_account', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('position_id', name=op.f('pk_paper_position')),
    sa.UniqueConstraint('account_id', 'exchange_code', 'symbol', name='uq_paper_position_account_symbol'),
    schema='trading'
    )
    op.create_table('paper_trade',
    sa.Column('trade_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('exchange_code', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('trade_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('realized_profit_loss', sa.Numeric(precision=20, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('traded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading.paper_account.account_id'], name='fk_paper_trade_account', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['trading.paper_order.order_id'], name='fk_paper_trade_order', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('trade_id', name=op.f('pk_paper_trade')),
    schema='trading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_trade', schema='trading')
    op.drop_table('paper_position', schema='trading')
    op.drop_table('paper_account', schema='trading')
    # ### end Alembic commands ###
