"""create live trading transition table

Revision ID: f0591f0baeb2
Revises: d4482c3ad2a2
Create Date: 2026-07-15 22:29:45.680750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0591f0baeb2'
down_revision: Union[str, Sequence[str], None] = 'd4482c3ad2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_trading_transition',
    sa.Column('live_trading_transition_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('environment_code', sa.String(length=30), server_default=sa.text("'KIWOOM'"), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approval_phrase_hash', sa.String(length=128), nullable=True),
    sa.Column('max_order_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('max_daily_loss', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('validation_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disable_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('live_trading_transition_id', name=op.f('pk_live_trading_transition')),
    schema='operation'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_trading_transition', schema='operation')
    # ### end Alembic commands ###
