"""revision: n1b2c3d4e5f6

Live unattended authorization lease (24H operator-approved horizon).
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "n1b2c3d4e5f6"
down_revision = "o6p7q8r9s0t1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 이미 적용된 환경(수동 DDL)에서도 안전하게 재실행
    op.execute(
        sa.text(
            """
            CREATE TABLE IF NOT EXISTS operation.live_unattended_authorization (
              live_unattended_authorization_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              user_broker_account_id BIGINT NOT NULL,
              broker_code VARCHAR(30) NOT NULL,
              status_code VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
              enabled BOOLEAN NOT NULL DEFAULT true,
              entry_authorized BOOLEAN NOT NULL DEFAULT true,
              protective_exit_authorized BOOLEAN NOT NULL DEFAULT true,
              authorized_until TIMESTAMPTZ NOT NULL,
              renewal_interval_seconds INTEGER NOT NULL DEFAULT 3600,
              renewal_margin_seconds INTEGER NOT NULL DEFAULT 600,
              arm_lease_ttl_seconds INTEGER NOT NULL DEFAULT 3600,
              activation_renew_hours INTEGER NOT NULL DEFAULT 8,
              max_authorization_horizon_hours INTEGER NOT NULL DEFAULT 168,
              last_renewed_at TIMESTAMPTZ NULL,
              last_renewal_actor VARCHAR(100) NULL,
              last_renewal_detail JSONB NOT NULL DEFAULT '{}'::jsonb,
              approved_by VARCHAR(100) NOT NULL,
              approved_at TIMESTAMPTZ NOT NULL DEFAULT now(),
              approval_reason TEXT NULL,
              approval_phrase_hash VARCHAR(128) NULL,
              source_activation_id BIGINT NULL,
              revoked_at TIMESTAMPTZ NULL,
              revoked_by VARCHAR(100) NULL,
              revoke_reason VARCHAR(200) NULL,
              created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
              updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """
        )
    )
    op.execute(
        sa.text(
            "CREATE INDEX IF NOT EXISTS ix_op_live_unatt_uba "
            "ON operation.live_unattended_authorization (user_broker_account_id)"
        )
    )
    op.execute(
        sa.text(
            "CREATE INDEX IF NOT EXISTS ix_op_live_unatt_status "
            "ON operation.live_unattended_authorization (status_code, enabled)"
        )
    )
    op.execute(
        sa.text(
            "CREATE UNIQUE INDEX IF NOT EXISTS uq_op_live_unatt_uba_active "
            "ON operation.live_unattended_authorization "
            "(user_broker_account_id) "
            "WHERE enabled = true AND status_code = 'ACTIVE'"
        )
    )


def downgrade() -> None:
    op.execute(
        sa.text(
            "DROP INDEX IF EXISTS operation.uq_op_live_unatt_uba_active"
        )
    )
    op.drop_index(
        "ix_op_live_unatt_status",
        table_name="live_unattended_authorization",
        schema="operation",
    )
    op.drop_index(
        "ix_op_live_unatt_uba",
        table_name="live_unattended_authorization",
        schema="operation",
    )
    op.drop_table("live_unattended_authorization", schema="operation")
