"""revision: p7q8r9s0t1u2

UPBIT full-market dynamic LIVE assignment / candidate selection / position binding.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "p7q8r9s0t1u2"
down_revision = "n7u8n9a0t1e2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        sa.text(
            """
            CREATE TABLE IF NOT EXISTS operation.upbit_full_market_assignment (
              assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              user_broker_account_id BIGINT NOT NULL,
              broker_code VARCHAR(30) NOT NULL DEFAULT 'UPBIT',
              strategy_id BIGINT NULL,
              deployment_id BIGINT NULL,
              mode VARCHAR(40) NOT NULL DEFAULT 'FIXED_SYMBOL',
              state VARCHAR(40) NOT NULL DEFAULT 'IDLE',
              template_symbol VARCHAR(40) NULL,
              current_symbol VARCHAR(40) NULL,
              active_selection_id BIGINT NULL,
              last_scanner_run_id VARCHAR(64) NULL,
              ai_live_gate_mode VARCHAR(20) NOT NULL DEFAULT 'ENFORCE',
              warmup_ready BOOLEAN NOT NULL DEFAULT false,
              market_data_fresh BOOLEAN NOT NULL DEFAULT false,
              signals_paused BOOLEAN NOT NULL DEFAULT false,
              cooldown_until TIMESTAMPTZ NULL,
              selection_lease_token VARCHAR(64) NULL,
              selection_lease_until TIMESTAMPTZ NULL,
              block_reason VARCHAR(200) NULL,
              last_error TEXT NULL,
              policy_json JSONB NOT NULL DEFAULT '{}'::jsonb,
              enabled_at TIMESTAMPTZ NULL,
              enabled_by VARCHAR(100) NULL,
              disabled_at TIMESTAMPTZ NULL,
              disabled_by VARCHAR(100) NULL,
              created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
              updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
              CONSTRAINT uq_upbit_fma_uba UNIQUE (user_broker_account_id)
            )
            """
        )
    )
    op.execute(
        sa.text(
            "CREATE INDEX IF NOT EXISTS ix_upbit_fma_mode_state "
            "ON operation.upbit_full_market_assignment (mode, state)"
        )
    )

    op.execute(
        sa.text(
            """
            CREATE TABLE IF NOT EXISTS operation.upbit_live_candidate_selection (
              selection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              user_broker_account_id BIGINT NOT NULL,
              strategy_id BIGINT NULL,
              deployment_id BIGINT NULL,
              scanner_run_id VARCHAR(64) NOT NULL,
              symbol VARCHAR(40) NOT NULL,
              rank INTEGER NULL,
              score DOUBLE PRECISION NULL,
              market_data_timestamp TIMESTAMPTZ NULL,
              liquidity DOUBLE PRECISION NULL,
              technical_metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
              ai_analysis_id BIGINT NULL,
              ai_recommendation VARCHAR(20) NULL,
              confidence DOUBLE PRECISION NULL,
              selected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
              selection_reason VARCHAR(200) NULL,
              source VARCHAR(64) NOT NULL DEFAULT 'UPBIT_OPPORTUNITY_SCANNER',
              status VARCHAR(30) NOT NULL DEFAULT 'SELECTED',
              skip_trace JSONB NOT NULL DEFAULT '[]'::jsonb,
              created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
              CONSTRAINT uq_upbit_lcs_uba_run_symbol
                UNIQUE (user_broker_account_id, scanner_run_id, symbol)
            )
            """
        )
    )
    op.execute(
        sa.text(
            "CREATE INDEX IF NOT EXISTS ix_upbit_lcs_uba_status "
            "ON operation.upbit_live_candidate_selection "
            "(user_broker_account_id, status)"
        )
    )

    op.execute(
        sa.text(
            """
            CREATE TABLE IF NOT EXISTS operation.upbit_strategy_position_binding (
              binding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              user_broker_account_id BIGINT NOT NULL,
              strategy_id BIGINT NULL,
              deployment_id BIGINT NULL,
              selection_id BIGINT NULL,
              symbol VARCHAR(40) NOT NULL,
              status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
              entry_order_id BIGINT NULL,
              opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),
              closed_at TIMESTAMPTZ NULL,
              meta_json JSONB NOT NULL DEFAULT '{}'::jsonb
            )
            """
        )
    )
    # OPEN 바인딩만 심볼당 1개 (부분 unique)
    op.execute(
        sa.text(
            "CREATE UNIQUE INDEX IF NOT EXISTS uq_upbit_spb_uba_symbol_open "
            "ON operation.upbit_strategy_position_binding "
            "(user_broker_account_id, symbol) "
            "WHERE status = 'OPEN'"
        )
    )


def downgrade() -> None:
    op.execute(
        sa.text(
            "DROP INDEX IF EXISTS operation.uq_upbit_spb_uba_symbol_open"
        )
    )
    op.execute(
        sa.text(
            "DROP TABLE IF EXISTS operation.upbit_strategy_position_binding"
        )
    )
    op.execute(
        sa.text(
            "DROP TABLE IF EXISTS operation.upbit_live_candidate_selection"
        )
    )
    op.execute(
        sa.text(
            "DROP INDEX IF EXISTS operation.ix_upbit_fma_mode_state"
        )
    )
    op.execute(
        sa.text(
            "DROP TABLE IF EXISTS operation.upbit_full_market_assignment"
        )
    )
