"""revision: q8r9s0t1u2v3

UPBIT portfolio policy + position slots + binding.slot_id (additive).
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "q8r9s0t1u2v3"
down_revision = "p7q8r9s0t1u2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        sa.text(
            """
            CREATE TABLE IF NOT EXISTS operation.upbit_portfolio_policy (
              policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              user_broker_account_id BIGINT NOT NULL,
              enabled BOOLEAN NOT NULL DEFAULT false,
              max_positions INTEGER NOT NULL DEFAULT 3,
              portfolio_capital_limit_krw DOUBLE PRECISION NULL,
              per_position_target_pct DOUBLE PRECISION NOT NULL DEFAULT 0.08,
              max_symbol_exposure_pct DOUBLE PRECISION NOT NULL DEFAULT 0.12,
              max_total_exposure_pct DOUBLE PRECISION NOT NULL DEFAULT 0.30,
              min_cash_reserve_pct DOUBLE PRECISION NOT NULL DEFAULT 0.60,
              daily_loss_limit_pct DOUBLE PRECISION NOT NULL DEFAULT 0.02,
              consecutive_loss_limit INTEGER NOT NULL DEFAULT 3,
              allow_averaging_down BOOLEAN NOT NULL DEFAULT false,
              allow_duplicate_symbol BOOLEAN NOT NULL DEFAULT false,
              entry_cooldown_seconds INTEGER NOT NULL DEFAULT 300,
              candidate_max_age_seconds INTEGER NOT NULL DEFAULT 1800,
              portfolio_max_pending_entries INTEGER NOT NULL DEFAULT 1,
              portfolio_daily_entry_limit INTEGER NOT NULL DEFAULT 10,
              entry_state VARCHAR(30) NOT NULL DEFAULT 'RUNNING',
              consecutive_loss_count INTEGER NOT NULL DEFAULT 0,
              -- future-ready nullable JSON policy bag (groups / overlays)
              risk_group_policy_json JSONB NOT NULL DEFAULT '{}'::jsonb,
              version INTEGER NOT NULL DEFAULT 1,
              created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
              updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
              CONSTRAINT uq_upbit_portfolio_policy_uba UNIQUE (user_broker_account_id)
            )
            """
        )
    )
    # 이미 CREATE된 DB용 additive ALTER (idempotent)
    # Documented SQL:
    #   ALTER TABLE operation.upbit_portfolio_policy
    #   ADD COLUMN IF NOT EXISTS risk_group_policy_json JSONB NOT NULL DEFAULT '{}'::jsonb;
    op.execute(
        sa.text(
            """
            ALTER TABLE operation.upbit_portfolio_policy
            ADD COLUMN IF NOT EXISTS risk_group_policy_json
              JSONB NOT NULL DEFAULT '{}'::jsonb
            """
        )
    )

    op.execute(
        sa.text(
            """
            CREATE TABLE IF NOT EXISTS operation.upbit_position_slot (
              slot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              user_broker_account_id BIGINT NOT NULL,
              strategy_id BIGINT NULL,
              deployment_id BIGINT NULL,
              slot_no INTEGER NOT NULL,
              status VARCHAR(30) NOT NULL DEFAULT 'EMPTY',
              symbol VARCHAR(40) NULL,
              candidate_selection_id BIGINT NULL,
              scanner_run_id VARCHAR(64) NULL,
              ai_analysis_id BIGINT NULL,
              recommended_amount_krw DOUBLE PRECISION NULL,
              allocated_amount_krw DOUBLE PRECISION NULL,
              reserved_amount_krw DOUBLE PRECISION NULL,
              clamp_reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
              entry_order_id BIGINT NULL,
              position_binding_id BIGINT NULL,
              opened_at TIMESTAMPTZ NULL,
              closed_at TIMESTAMPTZ NULL,
              cooldown_until TIMESTAMPTZ NULL,
              version INTEGER NOT NULL DEFAULT 1,
              created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
              updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
              CONSTRAINT uq_upbit_position_slot_uba_no
                UNIQUE (user_broker_account_id, slot_no)
            )
            """
        )
    )
    # active symbol 중복 방지 (EMPTY/COOLDOWN 제외)
    op.execute(
        sa.text(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS uq_upbit_slot_uba_active_symbol
            ON operation.upbit_position_slot (user_broker_account_id, symbol)
            WHERE symbol IS NOT NULL
              AND status IN (
                'RESERVED', 'ENTRY_PENDING', 'OPEN', 'EXIT_PENDING'
              )
            """
        )
    )
    op.execute(
        sa.text(
            "CREATE INDEX IF NOT EXISTS ix_upbit_slot_uba_status "
            "ON operation.upbit_position_slot (user_broker_account_id, status)"
        )
    )

    op.execute(
        sa.text(
            """
            ALTER TABLE operation.upbit_strategy_position_binding
            ADD COLUMN IF NOT EXISTS slot_id BIGINT NULL
            """
        )
    )
    op.execute(
        sa.text(
            "CREATE INDEX IF NOT EXISTS ix_upbit_spb_slot_id "
            "ON operation.upbit_strategy_position_binding (slot_id)"
        )
    )


def downgrade() -> None:
    op.execute(
        sa.text(
            """
            ALTER TABLE operation.upbit_portfolio_policy
            DROP COLUMN IF EXISTS risk_group_policy_json
            """
        )
    )
    op.execute(
        sa.text(
            "DROP INDEX IF EXISTS operation.ix_upbit_spb_slot_id"
        )
    )
    op.execute(
        sa.text(
            "ALTER TABLE operation.upbit_strategy_position_binding "
            "DROP COLUMN IF EXISTS slot_id"
        )
    )
    op.execute(
        sa.text(
            "DROP INDEX IF EXISTS operation.uq_upbit_slot_uba_active_symbol"
        )
    )
    op.execute(
        sa.text(
            "DROP INDEX IF EXISTS operation.ix_upbit_slot_uba_status"
        )
    )
    op.execute(
        sa.text("DROP TABLE IF EXISTS operation.upbit_position_slot")
    )
    op.execute(
        sa.text("DROP TABLE IF EXISTS operation.upbit_portfolio_policy")
    )
