"""Waiting Lifecycle Forward Shadow Lab V1 — research constants (REAL policy 불변)."""

from __future__ import annotations

from datetime import datetime, timezone

LAB_ID = "WAITING_LIFECYCLE_FORWARD_SHADOW_LAB_V1"
RULE_VERSION = "waiting_lifecycle_shadow_v1"
MARKET_UPBIT = "UPBIT"
RESEARCH_ONLY_LABEL = "RESEARCH_ONLY"

FEATURE_KEY = "upbit_waiting_lifecycle_shadow"
# seed — get_or_create_feature_epoch가 기존 row 유지 (IMMUTABLE)
FEATURE_DEPLOY_EPOCH = datetime(2026, 8, 31, 13, 0, 0, tzinfo=timezone.utc)
FEATURE_DEPLOY_EPOCH_SOURCE = "wrk_20260831_waiting_lifecycle_shadow_lab_v1"

VARIANT_R0 = "R0"
VARIANT_R1 = "R1"
VARIANT_R2 = "R2"
VARIANT_R3 = "R3"
ALL_VARIANTS = (VARIANT_R0, VARIANT_R1, VARIANT_R2, VARIANT_R3)
SHADOW_SIM_VARIANTS = (VARIANT_R1, VARIANT_R2, VARIANT_R3)

# R0 = CURRENT REAL baseline (관측만, REAL release 불변)
R0_SOFT_STALE_SECONDS = 1800.0
R0_HARD_EXPIRE_SECONDS = 5400.0
R0_CONSECUTIVE_NO_SIGNAL = 3

# R1 — 30m stale / 90m absolute
R1_SOFT_STALE_SECONDS = 1800.0
R1_ABSOLUTE_EXPIRY_SECONDS = 5400.0

# R2 — 20m stale / 60m absolute
R2_SOFT_STALE_SECONDS = 1200.0
R2_ABSOLUTE_EXPIRY_SECONDS = 3600.0

# R3 = R1 + score replacement (연구용 margin)
R3_SOFT_STALE_SECONDS = R1_SOFT_STALE_SECONDS
R3_ABSOLUTE_EXPIRY_SECONDS = R1_ABSOLUTE_EXPIRY_SECONDS
R3_REPLACEMENT_SCORE_MARGIN = 10.0

SHADOW_CAPACITY = 10

COHORT_PRIMARY_FORWARD = "PRIMARY_FORWARD"
COHORT_PREEXISTING = "PREEXISTING_AT_ACTIVATION"

STATUS_ACTIVE = "ACTIVE"
STATUS_STALE = "STALE"
STATUS_EXPIRED = "EXPIRED"
STATUS_REPLACED = "REPLACED"
STATUS_SUCCESS_TERMINAL = "SUCCESS_TERMINAL"
STATUS_BLOCKED_FULL = "BLOCKED_FULL"  # never admitted (full slot event row optional)

TERMINAL_STATUSES = frozenset(
    {
        STATUS_EXPIRED,
        STATUS_REPLACED,
        STATUS_SUCCESS_TERMINAL,
    }
)

# event types
EVT_ENROLLED = "ENROLLED"
EVT_EVALUATED = "EVALUATED"
EVT_TECHNICAL_PASS = "TECHNICAL_PASS"
EVT_TECHNICAL_BLOCK = "TECHNICAL_BLOCK"
EVT_STALE = "STALE"
EVT_ABSOLUTE_EXPIRED = "ABSOLUTE_EXPIRED"
EVT_REPLACEMENT_ELIGIBLE = "REPLACEMENT_ELIGIBLE"
EVT_REPLACED = "REPLACED"
EVT_FULL_SLOT_BLOCK = "FULL_SLOT_BLOCK"
EVT_SHADOW_ADMITTED = "SHADOW_ADMITTED"
EVT_ENTRY_PASS = "ENTRY_PASS"
EVT_SIGNAL_EMITTED = "SIGNAL_EMITTED"
EVT_ORDER_INTENT = "ORDER_INTENT"
EVT_BUY_FILLED = "BUY_FILLED"
EVT_REAL_LATER_BOUGHT = "REAL_LATER_BOUGHT"
EVT_COUNTERFACTUAL_UNOBSERVABLE = "COUNTERFACTUAL_UNOBSERVABLE"
EVT_WOULD_ADMIT = "WOULD_ADMIT"
EVT_WOULD_BLOCK = "WOULD_BLOCK"
EVT_WOULD_REPLACE = "WOULD_REPLACE"
EVT_WOULD_EXPIRE_EXISTING = "WOULD_EXPIRE_EXISTING"

EARLY_REVIEW_N = 30
STRONG_REVIEW_N = 50

# event coalescing — 동일 (obs, type, decision, block) 최소 간격
EVENT_DEDUPE_SECONDS = 60.0
