/**
 * 사용자 화면 DISPLAY 라벨 사전.
 * API/DB/enum 원본값은 변경하지 않는다 — UI title/column만.
 */

export const UI_LABEL_KO = {
  portfolioSlots: "자동매매 후보 슬롯",
  slot: "슬롯",
  symbol: "종목",
  score: "점수",
  ai: "AI 판단",
  confidence: "신뢰도",
  ownership: "구분",
  status: "상태",
  waitingAge: "대기 시간",
  holdingAge: "보유 시간",
  ageTime: "경과 시간",
  lastEvaluated: "최근 평가",
  entryDecision: "매수 판단",
  blockReason: "차단 사유",
  reservedKrw: "예약 금액",
  orderId: "주문번호",
  order: "주문",
  autoPositions: "자동매매 보유 포지션",
  qty: "수량",
  quantity: "수량",
  entry: "진입가",
  entryPrice: "매수가",
  exitPrice: "매도가",
  current: "현재가",
  price: "가격",
  amount: "주문금액",
  side: "매수/매도",
  buy: "매수",
  sell: "매도",
  pnl: "손익(PnL)",
  realizedPnl: "실현 손익",
  unrealizedPnl: "평가 손익",
  grossPnl: "수수료 전 손익",
  netPnl: "순손익",
  fee: "수수료",
  returnPct: "수익률",
  winRate: "승률",
  profitFactor: "수익 팩터(PF)",
  allocated: "배정 금액",
  slTpTrailing: "손절 / 익절 / 트레일링",
  highest: "고점",
  exitMonitor: "청산 감시",
  binding: "포지션 바인딩",
  entryBlockSummary: "최근 매수 평가 차단 요약",
  broker: "거래소/증권사",
  account: "계좌",
  strategy: "전략",
  positions: "보유 포지션",
  createdAt: "주문시각",
  filledAt: "체결시각",
  // runtime cards
  h24: "24시간 자동운영",
  live: "실거래(LIVE)",
  arm: "자동주문 승인(ARM)",
  runtime: "자동매매 런타임",
  worker: "주문 처리",
  executionRunner: "주문 실행",
  feed: "실시간 시세",
  entryEvaluator: "매수조건 평가",
  readiness: "자동매매 준비상태",
  // risk / safety
  risk: "리스크",
  killSwitch: "긴급 중지(Kill Switch)",
  exposure: "투자 비중",
  maxOrderAmount: "최대 주문금액",
  maxPositions: "최대 보유 종목 수",
  dailyDrawdown: "일일 최대 손실",
  recovery: "장애 복구",
  conflict: "불일치",
  blocker: "차단 요인",
  // research
  entryForwardValidation: "진입 전략 Forward 검증",
  candidate: "검증 후보",
  progress: "검증 진행률",
  combined: "전체 표본",
  newSample: "신규 미사용 표본",
  baseline: "현재 기준 전략",
  candidateB1: "후보 B1",
  filterBenefit: "필터 개선 효과",
  earlyDump: "진입 직후 하락",
  promotion: "REAL 적용 검토",
  notReady: "표본 수집 중",
  reviewReady: "적용 검토 가능",
  scanner: "시장 스캐너",
  // common actions / empty
  refresh: "새로고침",
  details: "상세보기",
  preview: "미리보기",
  noData: "데이터가 없습니다.",
  loading: "불러오는 중...",
  loadFailed: "데이터를 불러오지 못했습니다.",
  rank: "순위",
  activation: "계좌 활성화",
  maxOrderAmountDaily: "일일 최대 주문금액",
  orderLimitV2: "주문 한도 V2",
  unknownOrder: "확인 필요 주문",
  resolvedPolicy: "적용 리스크 정책",
  allowed: "허용",
  blocked: "차단됨",
  system: "시스템",
  user: "사용자",
  averageHolding: "평균 보유시간",
  selection: "후보 선정",
  topCandidate: "상위 후보",
  sample: "표본",
  newUnseenSample: "신규 미사용 표본",
  shadow: "분석용(Shadow)",
  paper: "모의거래(Paper)",
  real: "실거래(REAL)",
} as const;

export const UI_TOOLTIP_KO = {
  arm: "실제 주문을 제출할 수 있도록 일정 시간 동안 승인된 상태입니다.",
  readiness:
    "LIVE, ARM, Runtime, 시세, Risk 등 실제 자동매매에 필요한 조건을 종합한 상태입니다.",
  reservedKrw: "매수 주문을 위해 포트폴리오 슬롯에 임시로 확보한 금액입니다.",
  mfe: "진입 후 가장 유리했던 최대 수익률입니다.",
  mae: "진입 후 가장 불리했던 최대 손실률입니다.",
  forward:
    "아직 REAL에 적용하지 않은 진입 후보를, 이후 시장 데이터로만 검증합니다.",
  shadow: "실주문 없이 분석용으로만 추적하는 가상 진입입니다.",
  live: "실제 자금으로 주문이 나갈 수 있는 실거래 모드입니다.",
  killSwitch: "전체 실거래를 즉시 막는 최상위 안전 장치입니다.",
} as const;
