"""STEP 8-5-16 — EOD Settlement 상수."""

from __future__ import annotations

from enum import StrEnum


class SettlementStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    SUCCEEDED_WITH_WARNINGS = "SUCCEEDED_WITH_WARNINGS"
    RETRY_PENDING = "RETRY_PENDING"
    FAILED = "FAILED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    SKIPPED = "SKIPPED"
    SUPERSEDED = "SUPERSEDED"


class SettlementType(StrEnum):
    KRX_EOD = "KRX_EOD"
    UPBIT_DAILY = "UPBIT_DAILY"
    PAPER_STOCK_EOD = "PAPER_STOCK_EOD"
    PAPER_CRYPTO_DAILY = "PAPER_CRYPTO_DAILY"


class SettlementIssueSeverity(StrEnum):
    CRITICAL = "CRITICAL"
    WARNING = "WARNING"
    INFO = "INFO"


class SettlementIssueType(StrEnum):
    ORDER_MISSING_LOCAL = "ORDER_MISSING_LOCAL"
    ORDER_MISSING_EXTERNAL = "ORDER_MISSING_EXTERNAL"
    ORDER_STATUS_MISMATCH = "ORDER_STATUS_MISMATCH"
    EXECUTION_MISSING_LOCAL = "EXECUTION_MISSING_LOCAL"
    EXECUTION_DUPLICATE = "EXECUTION_DUPLICATE"
    POSITION_QUANTITY_MISMATCH = "POSITION_QUANTITY_MISMATCH"
    POSITION_AVERAGE_PRICE_MISMATCH = "POSITION_AVERAGE_PRICE_MISMATCH"
    CASH_BALANCE_MISMATCH = "CASH_BALANCE_MISMATCH"
    LOCKED_BALANCE_MISMATCH = "LOCKED_BALANCE_MISMATCH"
    EQUITY_MISMATCH = "EQUITY_MISMATCH"
    FEE_MISMATCH = "FEE_MISMATCH"
    TAX_MISMATCH = "TAX_MISMATCH"
    AMBIGUOUS_ORDER_PRESENT = "AMBIGUOUS_ORDER_PRESENT"
    UNRESOLVED_ORDER_PRESENT = "UNRESOLVED_ORDER_PRESENT"
    STALE_MARKET_PRICE = "STALE_MARKET_PRICE"
    STALE_BROKER_SNAPSHOT = "STALE_BROKER_SNAPSHOT"
    BROKER_DATA_UNAVAILABLE = "BROKER_DATA_UNAVAILABLE"
    SNAPSHOT_UBA_MISMATCH = "SNAPSHOT_UBA_MISMATCH"
    SNAPSHOT_BROKER_MISMATCH = "SNAPSHOT_BROKER_MISMATCH"
    DEPOSITS_UNKNOWN = "DEPOSITS_UNKNOWN"
    CREDENTIAL_INVALID = "CREDENTIAL_INVALID"
    LOCK_NOT_ACQUIRED = "LOCK_NOT_ACQUIRED"
    LOCK_OWNERSHIP_LOST = "LOCK_OWNERSHIP_LOST"


# 성공을 막거나 Manual Review로 보내는 Issue
CRITICAL_ISSUE_TYPES = frozenset(
    {
        SettlementIssueType.ORDER_MISSING_LOCAL.value,
        SettlementIssueType.ORDER_MISSING_EXTERNAL.value,
        SettlementIssueType.ORDER_STATUS_MISMATCH.value,
        SettlementIssueType.EXECUTION_MISSING_LOCAL.value,
        SettlementIssueType.EXECUTION_DUPLICATE.value,
        SettlementIssueType.POSITION_QUANTITY_MISMATCH.value,
        SettlementIssueType.CASH_BALANCE_MISMATCH.value,
        SettlementIssueType.AMBIGUOUS_ORDER_PRESENT.value,
        SettlementIssueType.UNRESOLVED_ORDER_PRESENT.value,
        SettlementIssueType.BROKER_DATA_UNAVAILABLE.value,
        SettlementIssueType.STALE_BROKER_SNAPSHOT.value,
        SettlementIssueType.SNAPSHOT_UBA_MISMATCH.value,
        SettlementIssueType.SNAPSHOT_BROKER_MISMATCH.value,
        SettlementIssueType.CREDENTIAL_INVALID.value,
        SettlementIssueType.LOCK_OWNERSHIP_LOST.value,
        SettlementIssueType.EQUITY_MISMATCH.value,
    }
)

AMBIGUOUS_ORDER_STATUSES = frozenset(
    {
        "AMBIGUOUS_SUBMISSION",
        "REMOTE_LOOKUP_PENDING",
        "IDENTITY_CONFLICT",
    }
)

OPEN_ORDER_STATUSES = frozenset(
    {
        "CREATED",
        "PENDING",
        "SUBMITTING",
        "SENT",
        "ACCEPTED",
        "PARTIALLY_FILLED",
        "CANCEL_REQUESTED",
        "REPLACE_REQUESTED",
    }
)
