"""KIWOOM multi-symbol universe V1 — SHADOW/OBSERVE only."""

from __future__ import annotations

MARKET = "KIWOOM"
EXCHANGE_KRX = "KRX"
RULE_VERSION = "kiwoom_multi_symbol_universe_v1"
SOURCE_MULTI_SYMBOL_V1 = "MULTI_SYMBOL_V1"

# Golden Cross — Strategy 17579 semantics (변경 금지)
SHORT_MA_WINDOW = 5
LONG_MA_WINDOW = 20
MIN_COMPLETED_BARS = LONG_MA_WINDOW + 1

CROSS_STATE_ABOVE_NO_NEW = "ABOVE_NO_NEW_CROSS"
CROSS_STATE_BELOW = "BELOW"
CROSS_STATE_FRESH_CROSS = "FRESH_CROSS"
CROSS_STATE_INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"

BLOCK_NO_FRESH_GOLDEN_CROSS = "NO_FRESH_GOLDEN_CROSS"
BLOCK_ALREADY_POSITIONED = "ALREADY_POSITIONED"
BLOCK_PENDING_ORDER = "PENDING_ORDER"
BLOCK_INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
