"""STEP 8-5-12 — Ambiguous Order Lookup 결과 상수."""

from __future__ import annotations

from enum import StrEnum


class RemoteLookupStatus(StrEnum):
    NONE = "NONE"
    PENDING = "PENDING"
    FOUND_MATCHED = "FOUND_MATCHED"
    FOUND_MISMATCHED = "FOUND_MISMATCHED"
    NOT_FOUND_TRANSIENT = "NOT_FOUND_TRANSIENT"
    NOT_FOUND_FINAL = "NOT_FOUND_FINAL"
    RATE_LIMITED = "RATE_LIMITED"
    BLOCKED = "BLOCKED"
    TEMPORARY_UNAVAILABLE = "TEMPORARY_UNAVAILABLE"
    AUTH_FAILED = "AUTH_FAILED"
    CONFLICT = "CONFLICT"


class SubmissionAttemptResult(StrEnum):
    SUCCESS = "SUCCESS"
    REJECTED = "REJECTED"
    RATE_LIMITED = "RATE_LIMITED"
    AMBIGUOUS_TIMEOUT = "AMBIGUOUS_TIMEOUT"
    AMBIGUOUS_CONNECTION = "AMBIGUOUS_CONNECTION"
    AMBIGUOUS_5XX = "AMBIGUOUS_5XX"
    AMBIGUOUS_429 = "AMBIGUOUS_429"
    AUTH_FAILED = "AUTH_FAILED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    REMOTE_ORDER_FOUND = "REMOTE_ORDER_FOUND"
    REMOTE_ORDER_NOT_FOUND = "REMOTE_ORDER_NOT_FOUND"
    CONFLICT = "CONFLICT"
    DUPLICATE_SUBMIT_BLOCKED = "DUPLICATE_SUBMIT_BLOCKED"
    # STEP 8-5-14 — Resolver Scheduler (Remote Lookup / Lock)
    REMOTE_LOOKUP_STARTED = "REMOTE_LOOKUP_STARTED"
    REMOTE_LOOKUP_DEFERRED = "REMOTE_LOOKUP_DEFERRED"
    REMOTE_LOOKUP_CREDENTIAL_BLOCKED = "REMOTE_LOOKUP_CREDENTIAL_BLOCKED"
    REMOTE_LOOKUP_RATE_LIMITED = "REMOTE_LOOKUP_RATE_LIMITED"
    LOCK_ACQUIRED = "LOCK_ACQUIRED"
    LOCK_NOT_ACQUIRED = "LOCK_NOT_ACQUIRED"
    LOCK_OWNERSHIP_LOST = "LOCK_OWNERSHIP_LOST"
