"""Entry Signal Shadow — constants (RESEARCH_ONLY)."""

from __future__ import annotations

RULE_VERSION = "entry_signal_shadow_v1"
MARKET = "UPBIT"
RESEARCH_ONLY_LABEL = "RESEARCH_ONLY_NO_REAL_ORDER"

VARIANT_E0 = "E0"
VARIANT_E1 = "E1"
VARIANT_E2 = "E2"
VARIANT_E3 = "E3"
VARIANT_E4 = "E4"
ALL_VARIANTS = (VARIANT_E0, VARIANT_E1, VARIANT_E2, VARIANT_E3, VARIANT_E4)

STATUS_PENDING = "PENDING"
STATUS_COMPLETED = "COMPLETED"
STATUS_INSUFFICIENT_OUTCOME = "INSUFFICIENT_OUTCOME"

# future return windows (minutes)
OUTCOME_WINDOWS_MIN = (5, 15, 30, 60)

# fee SoT mirror — UpbitFeePolicy.DEFAULT_TAKER_RATE
FEE_TAKER_RATE = 0.0005
# round-trip fee pct (buy+sell) — same as exit churn research
FEE_RT_PCT = 0.10

FORWARD_SAMPLE_TARGET = 100

SOURCE_REPLAY = "HISTORICAL_REPLAY"
SOURCE_FORWARD = "FORWARD_NATURAL"
