# -*- coding: utf-8 -*-
"""UPBIT durable Exit Intent — MA_DEAD_CROSS bounded retry (WRK-014)."""

from __future__ import annotations

# Active — restart recovery / unique active guard
ACTIVE_STATUSES = frozenset(
    {
        "CONFIRMED",
        "ORDER_PENDING",
        "COOLDOWN",
        "REVALIDATING",
        "BLOCKED",
    }
)

TERMINAL_STATUSES = frozenset(
    {
        "COMPLETED",
        "CONDITION_CLEARED",
        "EXHAUSTED",
        "CANCELLED",
    }
)

STATUS_CONFIRMED = "CONFIRMED"
STATUS_ORDER_PENDING = "ORDER_PENDING"
STATUS_COOLDOWN = "COOLDOWN"
STATUS_REVALIDATING = "REVALIDATING"
STATUS_COMPLETED = "COMPLETED"
STATUS_CONDITION_CLEARED = "CONDITION_CLEARED"
STATUS_EXHAUSTED = "EXHAUSTED"
STATUS_CANCELLED = "CANCELLED"
STATUS_BLOCKED = "BLOCKED"

EXIT_REASON_MA_DEAD_CROSS = "MA_DEAD_CROSS"

# Initial SELL = attempt 0; retries 1..MAX_RETRIES
DEFAULT_MAX_RETRIES = 3
DEFAULT_COOLDOWN_SECONDS = 60

# Audit event codes
EVT_CREATED = "EXIT_INTENT_CREATED"
EVT_ORDER_LINKED = "EXIT_INTENT_ORDER_LINKED"
EVT_ZERO_FILL_CANCELLED = "EXIT_INTENT_ZERO_FILL_CANCELLED"
EVT_PARTIAL_FILL = "EXIT_INTENT_PARTIAL_FILL"
EVT_COOLDOWN = "EXIT_INTENT_COOLDOWN"
EVT_REVALIDATED = "EXIT_INTENT_REVALIDATED"
EVT_RETRY_SUBMITTED = "EXIT_INTENT_RETRY_SUBMITTED"
EVT_CONDITION_CLEARED = "EXIT_INTENT_CONDITION_CLEARED"
EVT_COMPLETED = "EXIT_INTENT_COMPLETED"
EVT_EXHAUSTED = "EXIT_INTENT_EXHAUSTED"
EVT_BLOCKED = "EXIT_INTENT_BLOCKED"
EVT_RECOVERED = "EXIT_INTENT_RECOVERED"

ATTEMPT_INITIAL = "INITIAL"
ATTEMPT_RETRY = "RETRY"
